import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const depList=(v:any):string[]=>Array.isArray(v)?v.map(String):[];
Deno.serve(async(req)=>{
  const H={'content-type':'application/json','cache-control':'no-store'};
  if(req.method!=='POST') return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
  const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
  const presented=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');
  if(!service||presented!==service) return new Response(JSON.stringify({ok:false,error:'service_role_required'}),{status:403,headers:H});
  const url=Deno.env.get('SUPABASE_URL')||''; const sb=createClient(url,service,{auth:{persistSession:false}});
  const project='contentflow',now=Date.now(),iso=(ms:number)=>new Date(ms).toISOString();
  const out:any={architecture:'THROUGHPUT_RECOVERY_LOOP_V4_LANE_SAFE',project,reconcile:null,root_causes:{},circuit_recovery:{eligible:0,half_opened:0},released:{blocked:0,planned:0},verification:{pending:0,ready_for_rara:0},throughput:{},incident_governance:{eligible_for_analysis:0,terminal_preserved:0},guardrails:{deferred_untouched:true,no_forced_completion:true,human_blocks_respected:true,tool_executor_lane_preserved:true,half_open_cooldown_minutes:15,max_attempts_terminal:true}};
  const rec=await sb.rpc('contentflow_master_reconcile',{p_project_key:project}); out.reconcile={ok:!rec.error,error:rec.error?.message||null,data:rec.data||null};
  const {data:rows,error}=await sb.from('contentflow_build_backlog').select('id,task_key,status,priority,depends_on,team,quality_score,runtime_verified,next_eligible_at,updated_at,execution_lane,completion_phase').eq('project_key',project);
  if(error)return new Response(JSON.stringify({ok:false,error:error.message,out}),{status:500,headers:H});
  const byKey=new Map((rows||[]).map((r:any)=>[String(r.task_key),r]));
  const {data:incs}=await sb.from('director_repair_incidents').select('id,task_key,status,requires_human,error_class,attempts,max_attempts').eq('project_key',project).in('status',['open','analyzing','needs_help']);
  const humanBlocked=new Set((incs||[]).filter((i:any)=>i.requires_human===true).map((i:any)=>String(i.task_key||'')));
  const {data:workers}=await sb.from('director_worker_queue').select('model_id,status,total_assignments,total_completions,last_quality_score').eq('status','ready');
  const viableWorkers=(workers||[]).filter((w:any)=>Number(w.last_quality_score||0)>=85||Number(w.total_completions||0)>=3);
  const {data:openStates}=await sb.from('contentflow_retry_state').select('backlog_task_id,task_key,last_model,attempt_count,updated_at,circuit_state').eq('project_key',project).eq('circuit_state','open');
  const halfOpen:any[]=[];
  for(const s of openStates||[]){const task:any=byKey.get(String(s.task_key));if(!task||task.execution_lane==='tool_executor'||humanBlocked.has(String(s.task_key)))continue;if(now-new Date(s.updated_at).getTime()<15*60_000)continue;const deps=depList(task.depends_on),depsSatisfied=deps.length===0||deps.every(d=>String((byKey.get(d) as any)?.status||'')==='completed');if(!depsSatisfied)continue;const alt=viableWorkers.find((w:any)=>String(w.model_id)!==String(s.last_model||''));if(!alt)continue;halfOpen.push({state:s,task,alternate:String(alt.model_id)});}
  out.circuit_recovery.eligible=halfOpen.length;
  for(const x of halfOpen.slice(0,20)){const u=await sb.from('contentflow_retry_state').update({circuit_state:'closed',attempt_count:0,next_retry_at:new Date().toISOString(),circuit_open_until:null,updated_at:new Date().toISOString()}).eq('backlog_task_id',x.state.backlog_task_id).eq('circuit_state','open');if(!u.error){await sb.from('contentflow_build_backlog').update({status:'ready',selected_model:null,next_eligible_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',x.task.id).in('status',['blocked','ready','planned','failed']);out.circuit_recovery.half_opened++;}}
  const {data:retry}=await sb.from('contentflow_retry_state').select('backlog_task_id,circuit_state'); const circuit=new Map((retry||[]).map((r:any)=>[Number(r.backlog_task_id),String(r.circuit_state||'closed')]));
  let blockedDepsSatisfied=0,blockedDepsMissing=0,plannedEligible=0,verificationPending=0,staleRunning=0,blockedOpenCircuit=0; const releaseBlocked:any[]=[],promotePlanned:any[]=[];
  for(const r of rows||[]){const status=String(r.status||'');if(status==='running'&&new Date(r.updated_at).getTime()<now-10*60_000)staleRunning++;if(status==='verification_required'){verificationPending++;continue;}if(status!=='blocked'&&status!=='planned')continue;if(String(r.execution_lane||'llm_artifact')==='tool_executor')continue;const deps=depList(r.depends_on),explicitDeps=deps.length>0,depsSatisfied=explicitDeps&&deps.every(d=>String((byKey.get(d) as any)?.status||'')==='completed'),depsMissing=explicitDeps&&deps.some(d=>!byKey.has(d));const parentLike=String(r.team||'').includes('parent_integration'),human=humanBlocked.has(String(r.task_key)),eligibleAt=!r.next_eligible_at||new Date(r.next_eligible_at).getTime()<=now,open=circuit.get(Number(r.id))==='open';if(status==='blocked'){if(open){blockedOpenCircuit++;continue;}if(depsSatisfied&&!human&&eligibleAt){blockedDepsSatisfied++;releaseBlocked.push(r);}else if(depsMissing)blockedDepsMissing++;}if(status==='planned'){const eligible=((explicitDeps&&depsSatisfied)||(!explicitDeps&&!parentLike));if(!open&&eligible&&!human&&eligibleAt){plannedEligible++;promotePlanned.push(r);}}}
  out.root_causes={blocked_with_satisfied_dependencies:blockedDepsSatisfied,blocked_by_open_circuit:blockedOpenCircuit,blocked_with_missing_dependencies:blockedDepsMissing,planned_but_eligible:plannedEligible,verification_gate_pending:verificationPending,stale_running_over_10m:staleRunning,human_required_open:humanBlocked.size};
  releaseBlocked.sort((a:any,b:any)=>Number(b.priority||0)-Number(a.priority||0));promotePlanned.sort((a:any,b:any)=>Number(b.priority||0)-Number(a.priority||0));
  for(const r of releaseBlocked.slice(0,20)){const u=await sb.from('contentflow_build_backlog').update({status:'ready',updated_at:new Date().toISOString()}).eq('id',r.id).eq('status','blocked');if(!u.error)out.released.blocked++;}
  for(const r of promotePlanned.slice(0,20)){const u=await sb.from('contentflow_build_backlog').update({status:'ready',updated_at:new Date().toISOString()}).eq('id',r.id).eq('status','planned');if(!u.error)out.released.planned++;}
  const evidenceReady=(rows||[]).filter((r:any)=>String(r.status)==='verification_required'&&Number(r.quality_score||0)>=85);out.verification.pending=verificationPending;out.verification.ready_for_rara=evidenceReady.length;
  const curStart=iso(now-30*60_000),prevStart=iso(now-60*60_000);const {count:curCompleted}=await sb.from('contentflow_builder_runs').select('id',{count:'exact',head:true}).eq('project_key',project).in('status',['review_required','completed']).gte('finished_at',curStart);const {count:prevCompleted}=await sb.from('contentflow_builder_runs').select('id',{count:'exact',head:true}).eq('project_key',project).in('status',['review_required','completed']).gte('finished_at',prevStart).lt('finished_at',curStart);const {count:readyCount}=await sb.from('contentflow_build_backlog').select('id',{count:'exact',head:true}).eq('project_key',project).eq('status','ready');const {count:runningCount}=await sb.from('contentflow_build_backlog').select('id',{count:'exact',head:true}).eq('project_key',project).eq('status','running');const {count:blockedCount}=await sb.from('contentflow_build_backlog').select('id',{count:'exact',head:true}).eq('project_key',project).eq('status','blocked');const cur=Number(curCompleted||0),prev=Number(prevCompleted||0),recovered=cur>0&&(prev===0||cur>=Math.max(1,Math.floor(prev*.8)));out.throughput={completed_last_30m:cur,completed_previous_30m:prev,ready:Number(readyCount||0),running:Number(runningCount||0),blocked:Number(blockedCount||0),recovered};
  if(!recovered){const actionable=(incs||[]).filter((i:any)=>['autonomy_no_progress','progress_stall'].includes(String(i.error_class))&&['open','analyzing'].includes(String(i.status))&&i.requires_human!==true&&Number(i.attempts||0)<Number(i.max_attempts||0));out.incident_governance.eligible_for_analysis=actionable.length;out.incident_governance.terminal_preserved=(incs||[]).filter((i:any)=>['autonomy_no_progress','progress_stall'].includes(String(i.error_class))&&(String(i.status)==='needs_help'||i.requires_human===true||Number(i.attempts||0)>=Number(i.max_attempts||0))).length;}else{await sb.from('director_repair_incidents').update({status:'resolved',resolved_at:new Date().toISOString(),updated_at:new Date().toISOString(),outcome:'throughput_recovered_with_verified_recent_completions',requires_human:false}).eq('project_key',project).in('error_class',['autonomy_no_progress','progress_stall']).in('status',['open','analyzing']);}
  return new Response(JSON.stringify({ok:true,out}),{headers:H});
});