import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type T="code"|"architecture"|"general"|"bulk";
type M={id:string,input:number,output:number,quality:number,speed:number,finality:number,roles:T[]};
type S={model_id:string,runs:number,successes:number,avg_quality:number,avg_latency_ms:number,avg_cost_usd:number};
const MODELS:M[]=[
  {id:"deepseek-v4-flash",input:.15,output:.30,quality:72,speed:92,finality:90,roles:["code","bulk","general"]},
  {id:"baidu/ernie-4.5-turbo-128k",input:.12,output:.49,quality:70,speed:84,finality:96,roles:["code","bulk","general"]},
  {id:"qwen3-30b-a3b",input:.11,output:.46,quality:78,speed:82,finality:35,roles:["general","bulk","code"]},
  {id:"MiniMax-M2.7",input:.32,output:1.28,quality:84,speed:72,finality:35,roles:["general","architecture"]},
  {id:"kimi-k2.7-code",input:.99,output:4.10,quality:92,speed:60,finality:75,roles:["code","architecture"]}
];
const JUDGE=MODELS.find(m=>m.id==="baidu/ernie-4.5-turbo-128k")!;
const classify=(s:string):T=>/code|código|typescript|sql|bug|function|api|test/i.test(s)?"code":/arquitect|diseñ|schema|orquest/i.test(s)?"architecture":/masiv|bulk|clasific|resum/i.test(s)?"bulk":"general";
const baseScore=(m:M,t:T)=>.35*(m.roles.includes(t)?100:45)+.25*m.quality+.15*m.speed+.15*m.finality+.10*Math.max(0,100-(m.input+m.output)*12);
const adaptiveScore=(m:M,t:T,s?:S)=>{const base=baseScore(m,t);if(!s||!s.runs)return{score:base,base,evidence:0,empirical:null};const successRate=Math.max(0,Math.min(100,(Number(s.successes)/Math.max(1,Number(s.runs)))*100));const q=Math.max(0,Math.min(100,Number(s.avg_quality)||0));const latencyScore=Math.max(0,100-(Number(s.avg_latency_ms)||0)/150);const costScore=Math.max(0,100-(Number(s.avg_cost_usd)||0)*100000);const empirical=.50*successRate+.30*q+.10*latencyScore+.10*costScore;const evidence=Math.min(.75,Number(s.runs)/8);return{score:base*(1-evidence)+empirical*evidence,base,evidence,empirical};};
const fingerprint=async(s:string)=>{const b=new TextEncoder().encode(s.trim().toLowerCase().replace(/\s+/g," "));const h=await crypto.subtle.digest("SHA-256",b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")};
const modelById=(id:string)=>MODELS.find(m=>m.id===id);
const costOf=(id:string,i:number,o:number)=>{const m=modelById(id);return m?((i/1e6)*m.input+(o/1e6)*m.output):0};
const parseJudge=(s:string)=>{try{const j=JSON.parse(s.match(/\{[\s\S]*\}/)?.[0]||"");return{pass:Boolean(j.pass),score:Math.max(0,Math.min(100,Number(j.score)||0)),reason:String(j.reason||"")}}catch{return{pass:false,score:0,reason:"judge_parse_failed"}}};
const refusalLike=(s:string)=>/^\s*(?:error\s*[:\-]|cannot comply\b|i cannot\b|i can['’]?t\b|no puedo\b|no es posible\b|lo siento,? no)/i.test(s);

Deno.serve(async(req)=>{
 const h={"content-type":"application/json","cache-control":"no-store"};
 if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"POST required"}),{status:405,headers:h});
 const auth=req.headers.get("Authorization")||"";const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});
 const {data:{user}}=await sb.auth.getUser();if(!user)return new Response(JSON.stringify({ok:false,error:"unauthorized"}),{status:401,headers:h});
 const key=Deno.env.get("NEXOROUTER_API_KEY");if(!key)return new Response(JSON.stringify({ok:false,error:"missing_api_key"}),{status:500,headers:h});
 const b=await req.json().catch(()=>({}));const task=String(b.task||"").trim();if(!task)return new Response(JSON.stringify({ok:false,error:"task required"}),{status:400,headers:h});
 const project=String(b.project_key||"contentflow").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,64)||"contentflow";const type:T=b.task_type||classify(task);const fp=await fingerprint(task);const qualityThreshold=Math.min(95,Math.max(60,Number(b.quality_threshold||80)));const maxOutput=Math.min(1200,Math.max(200,Number(b.max_output_tokens||700)));
 const preferred:string[]=Array.isArray(b.preferred_models)?b.preferred_models.map(String).filter((x:string)=>MODELS.some(m=>m.id===x)).slice(0,4):[];
 const {data:memory}=await sb.from("director_approved_solutions").select("id,solution,model_id,quality_score,usage_count").eq("project_key",project).eq("task_fingerprint",fp).gte("quality_score",qualityThreshold).maybeSingle();if(memory){await sb.from("director_approved_solutions").update({usage_count:(memory.usage_count||0)+1,last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",memory.id);return new Response(JSON.stringify({ok:true,project_key:project,task_type:type,selected_model:memory.model_id,from_memory:true,quality_score:Number(memory.quality_score),result:memory.solution,total_cost_usd:0,usage:{input_tokens:0,output_tokens:0,judge_input_tokens:0,judge_output_tokens:0,total_tokens:0}}),{status:200,headers:h});}
 const {data:budget}=await sb.from("director_budgets").select("monthly_budget_usd,max_run_cost_usd,is_enabled").eq("project_key",project).maybeSingle();const maxRun=Number(budget?.max_run_cost_usd??0.05);if(budget?.is_enabled){const now=new Date(),monthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString();const {data:monthRuns}=await sb.from("director_runs").select("total_cost_usd").eq("project_key",project).gte("created_at",monthStart);const spent=(monthRuns||[]).reduce((a:any,x:any)=>a+Number(x.total_cost_usd||0),0);if(spent>=Number(budget.monthly_budget_usd))return new Response(JSON.stringify({ok:false,error:"monthly_budget_reached",project_key:project,spent_usd:+spent.toFixed(8),budget_usd:Number(budget.monthly_budget_usd)}),{status:429,headers:h});}
 const {data:stats}=await sb.from("director_model_stats").select("model_id,runs,successes,avg_quality,avg_latency_ms,avg_cost_usd").eq("project_key",project).eq("task_type",type);const statMap=new Map<string,S>((stats||[]).map((s:any)=>[s.model_id,s as S]));
 const ranked=MODELS.filter(m=>m.id!==JUDGE.id||type!=="architecture").map(m=>{const a=adaptiveScore(m,type,statMap.get(m.id));return{...m,score:+a.score.toFixed(2),base_score:+a.base.toFixed(2),learning_evidence:+a.evidence.toFixed(3),empirical_score:a.empirical===null?null:+a.empirical.toFixed(2)}}).sort((a,b)=>{const ai=preferred.indexOf(a.id),bi=preferred.indexOf(b.id);if(ai>=0||bi>=0){if(ai<0)return 1;if(bi<0)return-1;if(ai!==bi)return ai-bi;}return b.score-a.score;});
 const attempts:any[]=[];let selected:string|null=null,result="",ok=false,finalQuality=0;const max=Math.min(Math.max(Number(b.max_candidates||3),1),4);const estIn=Math.max(1,Math.ceil(task.length/4));
 for(const m of ranked.slice(0,max)){const estCandidate=(estIn/1e6)*m.input+(maxOutput/1e6)*m.output;const estJudge=((estIn+maxOutput)/1e6)*JUDGE.input+(180/1e6)*JUDGE.output;if(estCandidate+estJudge>maxRun){attempts.push({model:m.id,score:m.score,skipped:true,reason:"estimated_run_cost_exceeds_limit",estimated_cost_usd:+(estCandidate+estJudge).toFixed(8)});continue}const st=Date.now();try{
   const r=await fetch("https://api.nexorouter.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:m.id,messages:[{role:"system",content:"Eres un agente de ContentFlow. Entrega únicamente la solución FINAL, concreta y verificable. No muestres razonamiento interno. Respeta literalmente el stack, el alcance y los límites pedidos. Si la tarea pide código, entrega código utilizable; puedes incluir manejo de errores sin que eso signifique que la respuesta sea un error."},{role:"user",content:task}],temperature:.1,max_tokens:maxOutput,reasoning_effort:"low"})});
   const d=await r.json();const u=d?.usage||{},i=Number(u.input_tokens??u.prompt_tokens??0),o=Number(u.output_tokens??u.completion_tokens??0);const choice=d?.choices?.[0]||{};const content=String(choice?.message?.content??"");const reasoning=String(choice?.message?.reasoning_content??"");const finish=choice?.finish_reason??null;const truncated=finish==="length"||(o>=Math.floor(maxOutput*.98));const basic=r.ok&&content.trim().length>=20&&!truncated&&!refusalLike(content);
   let judge={pass:false,score:0,reason:basic?"not_judged":"basic_gate_failed"};let ji=0,jo=0,jcost=0,jstatus=0;if(basic){const jr=await fetch("https://api.nexorouter.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:JUDGE.id,messages:[{role:"system",content:"Eres el Quality Gate independiente de ContentFlow. Evalúa EXCLUSIVAMENTE si la respuesta cumple los requisitos explícitos de la tarea y su contexto. No inventes requisitos adicionales, tecnologías, pruebas o formatos no pedidos. Rechaza errores factuales, contradicciones, código claramente incompatible con el stack indicado, respuestas incompletas o evasivas. Responde SOLO JSON válido: {\"pass\":boolean,\"score\":0-100,\"reason\":\"breve\"}."},{role:"user",content:`TAREA:\n${task}\n\nRESPUESTA CANDIDATA:\n${content}`}],temperature:0,max_tokens:180,reasoning_effort:"low"})});const jd=await jr.json();const ju=jd?.usage||{};ji=Number(ju.input_tokens??ju.prompt_tokens??0);jo=Number(ju.output_tokens??ju.completion_tokens??0);jstatus=jr.status;const jcontent=String(jd?.choices?.[0]?.message?.content??"");judge=parseJudge(jcontent);jcost=costOf(JUDGE.id,ji,jo);}
   const ccost=costOf(m.id,i,o),totalAttempt=ccost+jcost,latency=Date.now()-st,passed=basic&&judge.pass&&judge.score>=qualityThreshold;attempts.push({model:m.id,score:m.score,base_score:m.base_score,learning_evidence:m.learning_evidence,empirical_score:m.empirical_score,status:r.status,latency_ms:latency,input_tokens:i,output_tokens:o,cost_usd:+ccost.toFixed(8),finish_reason:finish,truncated,basic_gate:basic,reasoning_tokens_present:reasoning.length>0,judge_model:JUDGE.id,judge_status:jstatus,judge_input_tokens:ji,judge_output_tokens:jo,judge_cost_usd:+jcost.toFixed(8),quality_score:judge.score,quality_gate:passed,quality_reason:judge.reason,reply:content});await sb.rpc("record_director_model_stat",{p_project_key:project,p_task_type:type,p_model_id:m.id,p_success:passed,p_quality:judge.score,p_latency_ms:latency,p_cost_usd:totalAttempt});if(passed){selected=m.id;result=content;ok=true;finalQuality=judge.score;break}
 }catch(e){const latency=Date.now()-st;attempts.push({model:m.id,score:m.score,status:0,latency_ms:latency,quality_gate:false,error:String(e)});await sb.rpc("record_director_model_stat",{p_project_key:project,p_task_type:type,p_model_id:m.id,p_success:false,p_quality:0,p_latency_ms:latency,p_cost_usd:0});}}
 const total=+attempts.reduce((a,x)=>a+(x.cost_usd||0)+(x.judge_cost_usd||0),0).toFixed(8);
 const inputTokens=attempts.reduce((a,x)=>a+Number(x.input_tokens||0),0),outputTokens=attempts.reduce((a,x)=>a+Number(x.output_tokens||0),0),judgeInputTokens=attempts.reduce((a,x)=>a+Number(x.judge_input_tokens||0),0),judgeOutputTokens=attempts.reduce((a,x)=>a+Number(x.judge_output_tokens||0),0);const totalTokens=inputTokens+outputTokens+judgeInputTokens+judgeOutputTokens;
 const {error:logError}=await sb.from("director_runs").insert({user_id:user.id,project_key:project,task_type:type,task,selected_model:selected,fallback_used:attempts.filter(x=>!x.skipped).length>1,ok,total_cost_usd:total,input_tokens:inputTokens,output_tokens:outputTokens,judge_input_tokens:judgeInputTokens,judge_output_tokens:judgeOutputTokens,attempts});let memory_saved=false;if(ok){const {error:memError}=await sb.from("director_approved_solutions").insert({user_id:user.id,project_key:project,task_type:type,task_fingerprint:fp,task,solution:result,model_id:selected,quality_score:finalQuality,usage_count:0,last_used_at:new Date().toISOString()});memory_saved=!memError;}
 return new Response(JSON.stringify({ok,project_key:project,task_type:type,selected_model:selected,result,quality_score:finalQuality,fallback_used:attempts.filter(x=>!x.skipped).length>1,ranking:ranked.map(x=>({model:x.id,score:x.score,base_score:x.base_score,learning_evidence:x.learning_evidence,empirical_score:x.empirical_score})),attempts,total_cost_usd:total,usage:{input_tokens:inputTokens,output_tokens:outputTokens,judge_input_tokens:judgeInputTokens,judge_output_tokens:judgeOutputTokens,total_tokens:totalTokens},trace_saved:!logError,memory_saved,from_memory:false}),{status:ok?200:502,headers:h});
});