import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type ContentRequest={projectId:string;objective:string;channel:string;async?:boolean};
const GROUND_MODEL="baidu/ernie-4.5-turbo-128k", GROUND_IN=.12, GROUND_OUT=.49;
const modelCost=(i:number,o:number)=>(i/1e6)*GROUND_IN+(o/1e6)*GROUND_OUT;
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"POST, OPTIONS"};
const parseGate=(s:string)=>{try{const j=JSON.parse(s.match(/\{[\s\S]*\}/)?.[0]||"");return{pass:Boolean(j.pass),score:Math.max(0,Math.min(100,Number(j.score)||0)),unsupported:Array.isArray(j.unsupported_claims)?j.unsupported_claims.map(String).slice(0,12):[],reason:String(j.reason||"")}}catch{return{pass:false,score:0,unsupported:["gate_parse_failed"],reason:"gate_parse_failed"}}};

async function processGeneration(args:{sb:any,url:string,nexoKey:string,auth:string,userId:string,generationId:string,project:any,objective:string,channel:string}){
 const {sb,url,nexoKey,auth,generationId,project,objective,channel}=args;
 const sourceFacts=`PROYECTO: ${project.title}\nOBJETIVO DEL PROYECTO: ${project.goal||"no especificado"}\nCANAL: ${channel}\nSOLICUD DEL USUARIO: ${objective}`;
 const orchestratorObjective=`Crea el contenido solicitado usando SOLO los DATOS FUENTE. La creatividad de estilo está permitida, pero no hechos nuevos. No inventes cifras, fechas, ubicaciones, nombres propios, precios, descuentos, promociones, disponibilidad, procedencia, estadísticas, recetas, propiedades del producto ni frecuencia. Respeta exactamente la cantidad y formato de piezas solicitadas; no agregues Story/Reel/formatos adicionales si no se pidieron.\nDATOS FUENTE:\n${sourceFacts}`;
 const grounding=async(text:string)=>{const r=await fetch("https://api.nexorouter.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${nexoKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:GROUND_MODEL,temperature:0,max_tokens:260,reasoning_effort:"low",messages:[{role:"system",content:"Grounding Gate estricto. Una afirmación factual pasa SOLO si está textual o claramente lógicamente contenida en DATOS FUENTE. No uses conocimiento general para justificarla. Rechaza datos específicos no soportados y formatos extra no solicitados. Responde SOLO JSON {\"pass\":boolean,\"score\":0-100,\"unsupported_claims\":[\"...\"],\"reason\":\"breve\"}."},{role:"user",content:`DATOS FUENTE:\n${sourceFacts}\n\nCONTENIDO:\n${text}`} ]})});const d=await r.json();const u=d?.usage||{},i=u.input_tokens??u.prompt_tokens??0,o=u.output_tokens??u.completion_tokens??0;return{...parseGate(String(d?.choices?.[0]?.message?.content??"")),cost:modelCost(i,o),status:r.status}};
 try{
   const r=await fetch(`${url}/functions/v1/contentflow-agent-team`,{method:"POST",headers:{Authorization:auth,"Content-Type":"application/json"},body:JSON.stringify({project_key:project.id,objective:orchestratorObjective,channel})});
   const d=await r.json(); const candidate=String(d?.final_result||""); const baseOk=Boolean(r.ok&&d?.ok&&candidate); let editor:any=null,finalText=candidate;
   if(baseOk){const editorTask=`Actúa como Editor Final de Cumplimiento de ContentFlow. Reescribe el CANDIDATO para entregar EXACTAMENTE lo que solicita el usuario, sin piezas o formatos adicionales. Usa SOLO hechos explícitos de DATOS FUENTE. No añadas ni infieras datos específicos. Devuelve ÚNICAMENTE el contenido final publicable.\n\nDATOS FUENTE:\n${sourceFacts}\n\nCANDIDATO:\n${candidate}`;const er=await fetch(`${url}/functions/v1/contentflow-director`,{method:"POST",headers:{Authorization:auth,"Content-Type":"application/json"},body:JSON.stringify({project_key:project.id,task_type:"general",task:editorTask,quality_threshold:90,max_candidates:4,max_output_tokens:550,preferred_models:[GROUND_MODEL,"deepseek-v4-flash"]})});const ed=await er.json();editor={ok:Boolean(er.ok&&ed?.ok),model:ed?.selected_model||null,quality:Number(ed?.quality_score||0),cost:Number(ed?.total_cost_usd||0),result:String(ed?.result||"")};if(editor.ok)finalText=editor.result;}
   let ground=baseOk&&editor?.ok?await grounding(finalText):{pass:false,score:0,unsupported:[],reason:baseOk?"compliance_editor_failed":"orchestration_failed",cost:0,status:0};let repair:any=null;
   if(baseOk&&editor?.ok&&!ground.pass){const correctionTask=`El Grounding Gate encontró estas afirmaciones o desviaciones no permitidas:\n- ${ground.unsupported.join("\n- ")}\nReescribe usando SOLO DATOS FUENTE y entrega exactamente lo pedido. Devuelve solo contenido publicable.\n\nDATOS FUENTE:\n${sourceFacts}\n\nTEXTO:\n${finalText}`;const rr=await fetch(`${url}/functions/v1/contentflow-director`,{method:"POST",headers:{Authorization:auth,"Content-Type":"application/json"},body:JSON.stringify({project_key:project.id,task_type:"general",task:correctionTask,quality_threshold:90,max_candidates:4,max_output_tokens:500,preferred_models:[GROUND_MODEL,"deepseek-v4-flash"]})});const rd=await rr.json();repair={ok:Boolean(rr.ok&&rd?.ok),model:rd?.selected_model||null,quality:Number(rd?.quality_score||0),cost:Number(rd?.total_cost_usd||0),result:String(rd?.result||"")};if(repair.ok){finalText=repair.result;ground=await grounding(finalText)}}
   const ok=baseOk&&Boolean(editor?.ok)&&ground.pass; const model=String(repair?.model||editor?.model||d?.integration?.selected_model||"agent-team"),quality=Math.min(Number(editor?.quality||0),Number(ground.score||0)); const total=Number(d?.total_cost_usd||0)+Number(editor?.cost||0)+Number(ground.cost||0)+Number(repair?.cost||0);
   await sb.from("generations").update({status:ok?"completed":"failed",model,quality_score:quality,actual_cost_usd:total,orchestrator_run_id:d?.run_id||null,output_json:{objective,channel,agent_count:d?.agent_count||5,final_result:ok?finalText:null,orchestrator_result:candidate,teams:d?.teams||[],integration:d?.integration||null,compliance_editor:editor,grounding_gate:ground,repair,error:ok?null:(baseOk?"compliance_or_grounding_failed":"orchestration_failed")}}).eq("id",generationId);
   return {ok,generationId,runId:d?.run_id||null,result:ok?finalText:null,selectedModel:model,qualityScore:quality,totalCostUsd:+total.toFixed(8),agentCount:d?.agent_count||5,teams:d?.teams||[],complianceEditor:editor,groundingGate:ground,repair,error:ok?null:(baseOk?"compliance_or_grounding_failed":"orchestration_failed")};
 }catch(e){await sb.from("generations").update({status:"failed",output_json:{objective,channel,error:String(e)}}).eq("id",generationId);return{ok:false,generationId,error:"agent_team_unreachable",detail:String(e)}}
}

Deno.serve(async(req)=>{
 const headers={...cors,"content-type":"application/json","cache-control":"no-store"};
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers});
 if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"POST required"}),{status:405,headers});
 const auth=req.headers.get("Authorization")||"",url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,nexoKey=Deno.env.get("NEXOROUTER_API_KEY");
 const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}}); const {data:{user}}=await sb.auth.getUser();
 if(!user)return new Response(JSON.stringify({ok:false,error:"unauthorized"}),{status:401,headers}); if(!nexoKey)return new Response(JSON.stringify({ok:false,error:"missing_api_key"}),{status:500,headers});
 const body=(await req.json().catch(()=>null)) as ContentRequest|null; const projectId=String(body?.projectId||"").trim(),objective=String(body?.objective||"").trim(),channel=String(body?.channel||"").trim();
 if(!projectId||!objective||!channel)return new Response(JSON.stringify({ok:false,error:"projectId, objective and channel are required"}),{status:400,headers});
 const {data:project,error:pErr}=await sb.from("projects").select("id,title,goal").eq("id",projectId).maybeSingle(); if(pErr||!project)return new Response(JSON.stringify({ok:false,error:"project_not_found_or_forbidden"}),{status:404,headers});
 const {data:g,error:gErr}=await sb.from("generations").insert({user_id:user.id,project_id:project.id,provider:"nexorouter",model:"agent-team-pending",generation_type:`content:${channel}`.slice(0,120),status:"running",prompt_tokens:0,completion_tokens:0,actual_cost_usd:0,output_json:{objective,channel,agent_count:5}}).select("id").single();
 if(gErr||!g)return new Response(JSON.stringify({ok:false,error:"generation_create_failed",detail:gErr?.message}),{status:500,headers});
 const work=processGeneration({sb,url,nexoKey,auth,userId:user.id,generationId:g.id,project,objective,channel});
 if(body?.async===true){EdgeRuntime.waitUntil(work);return new Response(JSON.stringify({ok:true,accepted:true,status:"running",generationId:g.id,agentCount:5,statusEndpoint:`${url}/functions/v1/contentflow-status?generation_id=${g.id}`}),{status:202,headers});}
 const out=await work; return new Response(JSON.stringify(out),{status:out.ok?200:502,headers});
});