import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
async function callInternal(url:string,service:string,path:string,timeoutMs=5000,body:any={}){try{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeoutMs);const r=await fetch(`${url}/functions/v1/${path}`,{method:'POST',signal:ctl.signal,headers:{Authorization:`Bearer ${service}`,'Content-Type':'application/json'},body:JSON.stringify(body)});clearTimeout(t);return{status:r.status,body:await r.json().catch(()=>({}))}}catch(e){return{warning:String(e)}}}
async function runProject(sb:any,project:string){const holder=crypto.randomUUID();const o:any={project_key:project,architecture:'DURABLE_EXECUTION_CONTROL_LOOP_V1'};const lease=await sb.rpc('contentflow_control_lease_acquire_v1',{p_project_key:project,p_holder_token:holder,p_ttl_seconds:90});if(lease.error||lease.data!==true){o.skipped='control_lease_busy';o.lease_error=lease.error?.message||null;return o}try{
 const tr=await sb.rpc('contentflow_transport_recovery_v1',{p_project_key:project});o.transport_recovery={data:tr.data,error:tr.error?.message||null};
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 const waits=await sb.rpc('contentflow_reconcile_durable_waits_v1',{p_project_key:project});o.durable_waits={data:waits.data,error:waits.error?.message||null};
 const completion=await sb.rpc('contentflow_reconcile_completion_evidence_v3',{p_project_key:project,p_limit:100});o.completion_evidence={data:completion.data,error:completion.error?.message||null};
 const evidence=await sb.rpc('contentflow_precycle_evidence_reconcile',{p_project_key:project});o.evidence_precycle={data:evidence.data,error:evidence.error?.message||null};
 const norm=await sb.rpc('contentflow_normalize_dispatchability',{p_project_key:project});o.normalize={data:norm.data,error:norm.error?.message||null};
 const dr=await sb.rpc('contentflow_dependency_release_reconcile',{p_project_key:project});o.dependency_release={data:dr.data,error:dr.error?.message||null};
 const reasons=await sb.rpc('contentflow_blocked_reason_reconcile',{p_project_key:project});o.blocked_reasons={data:reasons.data,error:reasons.error?.message||null};
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 const pre=await sb.rpc('contentflow_master_reconcile',{p_project_key:project});o.pre_reconcile={data:pre.data,error:pre.error?.message||null};
 const c=await sb.rpc('contentflow_director_core_cycle_auto',{p_project_key:project});o.core={data:c.data,error:c.error?.message||null};
 const completion2=await sb.rpc('contentflow_reconcile_completion_evidence_v3',{p_project_key:project,p_limit:100});o.post_completion_evidence={data:completion2.data,error:completion2.error?.message||null};
 const waits2=await sb.rpc('contentflow_reconcile_durable_waits_v1',{p_project_key:project});o.post_durable_waits={data:waits2.data,error:waits2.error?.message||null};
 const post=await sb.rpc('contentflow_master_reconcile',{p_project_key:project});o.post_reconcile={data:post.data,error:post.error?.message||null};
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 const [{data:llm},{data:tool},{count:active},{data:lastCycle}]=await Promise.all([sb.rpc('contentflow_dispatchable_count',{p_project_key:project}),sb.rpc('contentflow_executable_tool_pending_count',{p_project_key:project}),sb.from('contentflow_builder_runs').select('id',{count:'exact',head:true}).eq('project_key',project).in('status',['claimed','running']),sb.from('director_cycle_runs').select('id,dispatched,status').eq('project_key',project).order('id',{ascending:false}).limit(1)]);
 o.health={llm_dispatchable:Number(llm||0),tool_executable:Number(tool||0),active_runs:Number(active||0),last_cycle:lastCycle?.[0]||null};return o
 }finally{try{await sb.rpc('contentflow_control_lease_release_v1',{p_project_key:project,p_holder_token:holder})}catch{}}}
Deno.serve(async(req)=>{const H={'content-type':'application/json','cache-control':'no-store'};if(!['GET','POST'].includes(req.method))return new Response('{}',{status:405,headers:H});const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return new Response(JSON.stringify({ok:false,error:'runtime_config_missing'}),{status:500,headers:H});const sb=createClient(url,service,{auth:{persistSession:false}});try{const now=new Date().toISOString();const {data:rows,error:e}=await sb.from('contentflow_build_backlog').select('project_key').in('status',['ready','planned','running','verification_required','blocked','deferred']);if(e)throw e;const projects=[...new Set((rows||[]).map((x:any)=>String(x.project_key||'')).filter(Boolean))];const results:any[]=[];for(const project of projects)results.push(await runProject(sb,project));
 const totalTool=results.reduce((a:number,x:any)=>a+Number(x?.health?.tool_executable||0),0);const evidenceWorkers=Math.min(2,Math.ceil(totalTool/4));if(evidenceWorkers>0)EdgeRuntime.waitUntil(Promise.all(Array.from({length:evidenceWorkers},()=>callInternal(url,service,'contentflow-evidence-tool-runner',120000))));
 const {count:reviews}=await sb.from('contentflow_review_work_queue').select('builder_run_id',{count:'exact',head:true}).eq('state','pending').lte('available_at',now);const since=new Date(Date.now()-30*60_000).toISOString();const {data:qa}=await sb.from('contentflow_nexo_request_metrics').select('model,success,semantic_success').eq('lane','qa').gte('created_at',since);let nreq=0,sem=0;const byModel:any={};for(const x of qa||[]){const m=String(x.model||'unknown');if(!byModel[m])byModel[m]={n:0,sem:0};byModel[m].n++;nreq++;if(x.semantic_success){byModel[m].sem++;sem++;}}let bestRate=0;for(const m of Object.keys(byModel))bestRate=Math.max(bestRate,byModel[m].sem/Math.max(1,byModel[m].n));const degraded=nreq>=20&&(sem/Math.max(1,nreq)<0.20||bestRate<0.20);const reviewCap=degraded?1:3;const n=Math.min(reviewCap,Number(reviews||0));if(degraded&&Number(reviews||0)>0){for(const p of projects){try{await sb.rpc('contentflow_learn_qa_health_degradation',{p_project_key:p,p_task_key:'review_queue',p_evidence:`qa_semantic_rate=${sem/Math.max(1,nreq)} best_rate=${bestRate} pending=${reviews}`})}catch{}}}if(n)EdgeRuntime.waitUntil(Promise.all(Array.from({length:n},()=>callInternal(url,service,'contentflow-rara',120000))));return new Response(JSON.stringify({ok:true,architecture:'DURABLE_EXECUTION_CONTROL_LOOP_V1',projects_discovered:projects,project_results:results,evidence_workers_scheduled:evidenceWorkers,review_workers_scheduled:n,qa_backpressure:{degraded,review_cap:reviewCap,total:nreq,semantic_ok:sem,best_rate:bestRate,by_model:byModel}}),{headers:H});}catch(err){return new Response(JSON.stringify({ok:false,architecture:'DURABLE_EXECUTION_CONTROL_LOOP_V1',error:String(err)}),{status:500,headers:H})}});
