import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
import {evaluateAutonomyAdmission} from "../_shared/autonomy-admission.mjs";

const ARCH='DURABLE_EXECUTION_CONTROL_LOOP_V12_EXTERNAL_HANDOFF_RETRY_ISOLATION';
const RECOVERY_RAW_BASE='https://raw.githubusercontent.com/investmentsespana-stack/-contentflow/main/backups';

async function callInternal(url:string,service:string,path:string,timeoutMs=5000,body:any={}){try{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeoutMs);const r=await fetch(`${url}/functions/v1/${path}`,{method:'POST',signal:ctl.signal,headers:{Authorization:`Bearer ${service}`,'Content-Type':'application/json'},body:JSON.stringify(body)});clearTimeout(t);return{status:r.status,body:await r.json().catch(()=>({}))}}catch(e){return{warning:String(e)}}}

async function budgetSnapshot(sb:any,project:string){const {data:b,error}=await sb.from('director_budgets').select('monthly_budget_usd,max_run_cost_usd,is_enabled,updated_at').eq('project_key',project).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)return{configured:false,enabled:false,telemetry_error:error.message};if(!b)return{configured:false,enabled:false,enforcement:'not_configured'};const since=new Date(new Date().getUTCFullYear(),new Date().getUTCMonth(),1).toISOString();const {data:m,error:me}=await sb.from('contentflow_nexo_request_metrics').select('cost_usd').gte('created_at',since);if(me)return{configured:true,enabled:Boolean(b.is_enabled),monthly_budget_usd:Number(b.monthly_budget_usd),max_run_cost_usd:Number(b.max_run_cost_usd),telemetry_error:me.message};const spent=(m||[]).reduce((s:number,x:any)=>s+Number(x.cost_usd||0),0);return{configured:true,enabled:Boolean(b.is_enabled),monthly_budget_usd:Number(b.monthly_budget_usd),max_run_cost_usd:Number(b.max_run_cost_usd),spent_month_usd:spent}}

function recoverySnapshotFacts(row:any){const e=row?.evidence||row||{};const created=String(e.created_at_utc||e.createdAtUtc||'');const ts=Date.parse(created);const age=Number.isFinite(ts)?Date.now()-ts:Number.POSITIVE_INFINITY;const passed=e.passed===true;const rollback=e.rollback_plan_viable===true||e.rollbackPlanViable===true;const replay=e.deterministic_replay_viable===true||e.deterministicReplayViable===true;const project=String(e.project_ref||e.projectRef||'koqpyfvnprmirqviafzq');return{fresh:(row?.verified===undefined||row?.verified===true)&&(row?.status===undefined||String(row.status).toLowerCase()==='pass')&&passed&&rollback&&replay&&project==='koqpyfvnprmirqviafzq'&&age>=0&&age<=36*60*60*1000,created,age,passed,rollback,replay,project,evidence:e}}

async function ensureFreshRecoverySnapshot(sb:any){const existing=await sb.from('director_external_evidence').select('status,verified,updated_at,evidence').eq('project_key','contentflow').eq('evidence_type','recovery_snapshot').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!existing.error&&recoverySnapshotFacts(existing.data).fresh)return{row:existing.data,source:'db'};const day=new Date().toISOString().slice(0,10);const url=`${RECOVERY_RAW_BASE}/${day}/recovery-verification.json`;try{const r=await fetch(url,{headers:{'cache-control':'no-cache'}});if(!r.ok)return{row:existing.data||null,source:'db_stale',warning:`snapshot_http_${r.status}`};const e=await r.json();const facts=recoverySnapshotFacts(e);if(!facts.fresh)return{row:existing.data||null,source:'github_rejected',warning:'snapshot_contract_invalid'};const normalized={passed:true,architecture:String(e.architecture||''),created_at_utc:facts.created,project_ref:facts.project,rollback_plan_viable:true,deterministic_replay_viable:true,repo_migration_cutoff:String(e.repoMigrationCutoff||''),database_migration_head:String(e.databaseMigrationHead||''),artifact_path:`backups/${day}/recovery-verification.json`};const taskKey=`recovery_snapshot_${day.replaceAll('-','_')}`;const prior=await sb.from('director_external_evidence').select('id').eq('project_key','contentflow').eq('task_key',taskKey).eq('evidence_type','recovery_snapshot').limit(1).maybeSingle();if(prior.data?.id){await sb.from('director_external_evidence').update({updated_at:new Date().toISOString(),status:'pass',verified:true,evidence:normalized,source:`github:${normalized.artifact_path}`}).eq('id',prior.data.id)}else{await sb.from('director_external_evidence').insert({project_key:'contentflow',task_key:taskKey,evidence_type:'recovery_snapshot',environment:'production',engine:'github-actions',version:'recovery-snapshot-migration-replay-v2',status:'pass',evidence:normalized,source:`github:${normalized.artifact_path}`,verified:true})}return{row:{status:'pass',verified:true,evidence:normalized},source:'github_refreshed'}}catch(err){return{row:existing.data||null,source:'db_stale',warning:String(err)}}}

async function collectAdmissionSignals(sb:any){const errors:string[]=[];const recovery=await sb.from('director_external_evidence').select('status,verified,updated_at,evidence').eq('project_key','contentflow').eq('evidence_type','recovery_certification').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(recovery.error)errors.push(`recovery:${recovery.error.message}`);const snapshotState=await ensureFreshRecoverySnapshot(sb);const snapshotFacts=recoverySnapshotFacts(snapshotState.row);if(snapshotState.warning&&!snapshotFacts.fresh)errors.push(`recovery_snapshot:${snapshotState.warning}`);const budget=await budgetSnapshot(sb,'contentflow');if(budget.telemetry_error&&budget.configured)errors.push(`provider_budget:${budget.telemetry_error}`);const activeRuns=await sb.from('contentflow_builder_runs').select('backlog_task_id,status').eq('project_key','contentflow').in('status',['claimed','running','review_required']).is('finished_at',null);if(activeRuns.error)errors.push(`active_runs:${activeRuns.error.message}`);const counts=new Map<number,number>();for(const r of activeRuns.data||[]){const id=Number(r.backlog_task_id);counts.set(id,(counts.get(id)||0)+1)}const ownershipConflicts=Array.from(counts.values()).filter(n=>n>1).length;const incidents=await sb.from('director_repair_incidents').select('id,risk_level,requires_human,task_key').eq('project_key','contentflow').in('status',['open','analyzing']);if(incidents.error)errors.push(`incidents:${incidents.error.message}`);const incidentRows=incidents.data||[];const blockingIncidents=incidentRows.filter((x:any)=>x.requires_human===true||String(x.risk_level)==='critical').length;

  const retrySince=new Date(Date.now()-60*60*1000).toISOString();
  const recentRuns=await sb.from('contentflow_builder_runs').select('id,backlog_task_id').eq('project_key','contentflow').gte('created_at',retrySince);
  if(recentRuns.error)errors.push(`retry_runs:${recentRuns.error.message}`);
  const runRows=recentRuns.data||[];
  const backlogIds=[...new Set(runRows.map((x:any)=>Number(x.backlog_task_id)).filter(Number.isFinite))];
  const backlogMeta=new Map<number,any>();
  if(backlogIds.length){const meta=await sb.from('contentflow_build_backlog').select('id,epic,execution_lane,blocked_reason').in('id',backlogIds);if(meta.error)errors.push(`retry_backlog:${meta.error.message}`);for(const x of meta.data||[])backlogMeta.set(Number(x.id),x)}
  const systemicRunIds:number[]=[];const isolatedRunIds:number[]=[];
  for(const x of runRows){const m=backlogMeta.get(Number(x.backlog_task_id));if(String(m?.epic||'')==='external_handoff')isolatedRunIds.push(Number(x.id));else systemicRunIds.push(Number(x.id))}
  let retryRows:any[]=[];
  if(systemicRunIds.length){const retries=await sb.from('contentflow_retry_state').select('last_run_id,circuit_state').eq('project_key','contentflow').in('last_run_id',systemicRunIds);if(retries.error)errors.push(`retry_state:${retries.error.message}`);retryRows=retries.data||[]}
  let isolatedOpenCircuits=0;
  if(isolatedRunIds.length){const isolated=await sb.from('contentflow_retry_state').select('last_run_id,circuit_state').eq('project_key','contentflow').in('last_run_id',isolatedRunIds);if(isolated.error)errors.push(`isolated_retry_state:${isolated.error.message}`);isolatedOpenCircuits=(isolated.data||[]).filter((r:any)=>String(r.circuit_state)==='open').length}
  const retryStates=retryRows.length,openCircuits=retryRows.filter((r:any)=>String(r.circuit_state)==='open').length;

  const policy=await sb.from('director_control_policy').select('desired_running').eq('project_key','contentflow').maybeSingle();if(policy.error)errors.push(`control_policy:${policy.error.message}`);const canary=await sb.from('director_canary_policy').select('stable_parallelism').eq('project_key','contentflow').maybeSingle();if(canary.error)errors.push(`canary_policy:${canary.error.message}`);return{telemetryHealthy:errors.length===0,telemetryErrors:errors,recoveryReceipt:recovery.data?.evidence||{},freshRecoverySnapshot:snapshotFacts.fresh,recoverySnapshot:snapshotFacts.evidence||{},recoverySnapshotSource:snapshotState.source,budget,ownershipConflicts,openIncidents:blockingIncidents,informationalIncidents:incidentRows.length,openCircuits,retryStates,isolatedOpenCircuits,waitingForEvidence:0,requestedParallelism:Number(policy.data?.desired_running||0),stableParallelism:Number(canary.data?.stable_parallelism||2),minimumDwellMs:5*60*1000,retryWindowMinutes:60}}

async function runProject(sb:any,url:string,service:string,project:string){const holder=crypto.randomUUID();const o:any={project_key:project,architecture:ARCH};const lease=await sb.rpc('contentflow_control_lease_acquire_v1',{p_project_key:project,p_holder_token:holder,p_ttl_seconds:75});if(lease.error||lease.data!==true){o.skipped='control_lease_busy';o.lease_error=lease.error?.message||null;return o}try{const tr=await sb.rpc('contentflow_transport_recovery_v1',{p_project_key:project});o.transport_recovery={data:tr.data,error:tr.error?.message||null};const waits=await sb.rpc('contentflow_reconcile_durable_waits_v1',{p_project_key:project});o.durable_waits={data:waits.data,error:waits.error?.message||null};const norm=await sb.rpc('contentflow_normalize_dispatchability',{p_project_key:project});o.normalize={data:norm.data,error:norm.error?.message||null};const dr=await sb.rpc('contentflow_dependency_release_reconcile',{p_project_key:project});o.dependency_release={data:dr.data,error:dr.error?.message||null};let runCore=true;if(project==='contentflow'){const signals=await collectAdmissionSignals(sb);const admission=evaluateAutonomyAdmission(signals);o.admission={...admission,telemetry_errors:signals.telemetryErrors,informational_incidents:signals.informationalIncidents,retry_window_minutes:signals.retryWindowMinutes,recovery_snapshot:signals.recoverySnapshot,recovery_snapshot_source:signals.recoverySnapshotSource,isolated_external_handoff_open_circuits:signals.isolatedOpenCircuits};if(admission.admitted){o.planner={skipped:true,reason:'single_writer_core_owns_idle_replan'}}else{o.planner={skipped:true,reason:'autonomy_admission_denied'};o.core={skipped:true,reason:'safety_gate',blockers:admission.blockers};runCore=false}}if(runCore){const c=await sb.rpc('contentflow_director_core_cycle_auto',{p_project_key:project});o.core={data:c.data,error:c.error?.message||null}}const [{data:llm},{data:tool},{count:active},{data:lastCycle}]=await Promise.all([sb.rpc('contentflow_dispatchable_count',{p_project_key:project}),sb.rpc('contentflow_executable_tool_pending_count',{p_project_key:project}),sb.from('contentflow_builder_runs').select('id',{count:'exact',head:true}).eq('project_key',project).in('status',['claimed','running']),sb.from('director_cycle_runs').select('id,dispatched,status').eq('project_key',project).order('id',{ascending:false}).limit(1)]);o.health={llm_dispatchable:Number(llm||0),tool_executable:Number(tool||0),active_runs:Number(active||0),last_cycle:lastCycle?.[0]||null};return o}finally{try{await sb.rpc('contentflow_control_lease_release_v1',{p_project_key:project,p_holder_token:holder})}catch{}}}

Deno.serve(async(req)=>{const H={'content-type':'application/json','cache-control':'no-store'};if(!['GET','POST'].includes(req.method))return new Response('{}',{status:405,headers:H});const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return new Response(JSON.stringify({ok:false,error:'runtime_config_missing'}),{status:500,headers:H});const sb=createClient(url,service,{auth:{persistSession:false}});try{const now=new Date().toISOString();const activity=new Map<string,number>();let discoveryWarning:string|null=null;let projects:string[]=['contentflow'];try{const {data:rows,error:e}=await sb.from('contentflow_build_backlog').select('project_key,status').in('status',['ready','planned','running','verification_required']);if(e)throw e;for(const x of rows||[]){const p=String(x.project_key||'');if(p)activity.set(p,(activity.get(p)||0)+1)}const discovered=[...activity.keys()].sort((a,b)=>a==='contentflow'?-1:b==='contentflow'?1:(activity.get(b)||0)-(activity.get(a)||0));projects=[...new Set(['contentflow',...discovered])]}catch(e){discoveryWarning=String((e as any)?.message||e);projects=['contentflow']}const results:any[]=[];for(const project of projects){try{results.push(await runProject(sb,url,service,project))}catch(e){results.push({project_key:project,architecture:ARCH,error:String((e as any)?.message||e),isolated_failure:true})}}const evidenceProjects=results.filter((x:any)=>Number(x?.health?.tool_executable||0)>0).map((x:any)=>String(x.project_key)).slice(0,2);if(evidenceProjects.length)EdgeRuntime.waitUntil(Promise.all(evidenceProjects.map((project:string)=>callInternal(url,service,'contentflow-evidence-tool-runner',90000,{project_key:project}))));let reviewWorkers=0;try{const {count:reviews}=await sb.from('contentflow_review_work_queue').select('builder_run_id',{count:'exact',head:true}).eq('state','pending').lte('available_at',now);reviewWorkers=Math.min(2,Number(reviews||0));if(reviewWorkers)EdgeRuntime.waitUntil(Promise.all(Array.from({length:reviewWorkers},()=>callInternal(url,service,'contentflow-rara',90000))))}catch{}return new Response(JSON.stringify({ok:true,architecture:ARCH,projects_discovered:projects,activity:Object.fromEntries(activity),discovery_warning:discoveryWarning,project_results:results,evidence_projects_scheduled:evidenceProjects,review_workers_scheduled:reviewWorkers}),{headers:H})}catch(err){return new Response(JSON.stringify({ok:false,architecture:ARCH,error:String(err)}),{status:500,headers:H})}});
