import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
import {evaluateAutonomyAdmission} from "../_shared/autonomy-admission.mjs";

const CONTROL_PLANE_ARCH='MASTER_DIRECTOR_CONTROL_PLANE_V10_BUDGET_AWARE+DURABLE_EXECUTION_V2';

async function callInternal(url:string,service:string,path:string,timeoutMs=5000,body:any={}){try{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeoutMs);const r=await fetch(`${url}/functions/v1/${path}`,{method:'POST',signal:ctl.signal,headers:{Authorization:`Bearer ${service}`,'Content-Type':'application/json'},body:JSON.stringify(body)});clearTimeout(t);return{status:r.status,body:await r.json().catch(()=>({}))}}catch(e){return{warning:String(e)}}}

async function collectAdmissionSignals(sb:any){
 const errors:string[]=[];
 const recovery=await sb.from('director_external_evidence').select('status,verified,updated_at,evidence').eq('project_key','contentflow').eq('evidence_type','recovery_certification').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(recovery.error)errors.push(`recovery:${recovery.error.message}`);
 const budget=await sb.rpc('contentflow_budget_admission_snapshot',{p_project_key:'contentflow'});if(budget.error)errors.push(`provider_budget:${budget.error.message}`);
 const activeRuns=await sb.from('contentflow_builder_runs').select('backlog_task_id,status').eq('project_key','contentflow').in('status',['claimed','running','review_required']).is('finished_at',null);if(activeRuns.error)errors.push(`active_runs:${activeRuns.error.message}`);const counts=new Map<number,number>();for(const r of activeRuns.data||[]){const id=Number(r.backlog_task_id);counts.set(id,(counts.get(id)||0)+1)}const ownershipConflicts=Array.from(counts.values()).filter(n=>n>1).length;
 const incidents=await sb.from('director_repair_incidents').select('id',{count:'exact',head:true}).eq('project_key','contentflow').in('status',['open','analyzing']);if(incidents.error)errors.push(`incidents:${incidents.error.message}`);
 const retries=await sb.from('contentflow_retry_state').select('circuit_state').eq('project_key','contentflow');if(retries.error)errors.push(`retry_state:${retries.error.message}`);const retryStates=(retries.data||[]).length,openCircuits=(retries.data||[]).filter((r:any)=>String(r.circuit_state)==='open').length;
 const evidenceWait=await sb.from('contentflow_build_backlog').select('id',{count:'exact',head:true}).eq('project_key','contentflow').eq('status','WAITING_FOR_EVIDENCE_PRODUCER');if(evidenceWait.error)errors.push(`evidence_wait:${evidenceWait.error.message}`);
 const policy=await sb.from('director_control_policy').select('desired_running').eq('project_key','contentflow').maybeSingle();if(policy.error)errors.push(`control_policy:${policy.error.message}`);
 const canary=await sb.from('director_canary_policy').select('stable_parallelism').eq('project_key','contentflow').maybeSingle();if(canary.error)errors.push(`canary_policy:${canary.error.message}`);
 return{telemetryHealthy:errors.length===0,telemetryErrors:errors,recoveryReceipt:recovery.data?.evidence||{},budget:budget.data||{},ownershipConflicts,openIncidents:Number(incidents.count||0),openCircuits,retryStates,waitingForEvidence:Number(evidenceWait.count||0),requestedParallelism:Number(policy.data?.desired_running||0),stableParallelism:Number(canary.data?.stable_parallelism||2),minimumDwellMs:5*60*1000};
}

async function runProject(sb:any,url:string,service:string,project:string){const holder=crypto.randomUUID();const o:any={project_key:project,architecture:CONTROL_PLANE_ARCH};const lease=await sb.rpc('contentflow_control_lease_acquire_v1',{p_project_key:project,p_holder_token:holder,p_ttl_seconds:90});if(lease.error||lease.data!==true){o.skipped='control_lease_busy';o.lease_error=lease.error?.message||null;return o}try{
 const tomb=await sb.rpc('contentflow_retire_obsolete_evidence_tombstones_v1',{p_project_key:project});o.tombstones={data:tomb.data,error:tomb.error?.message||null};
 const tr=await sb.rpc('contentflow_transport_recovery_v1',{p_project_key:project});o.transport_recovery={data:tr.data,error:tr.error?.message||null};
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 const waits=await sb.rpc('contentflow_reconcile_durable_waits_v1',{p_project_key:project});o.durable_waits={data:waits.data,error:waits.error?.message||null};
 const completion=await sb.rpc('contentflow_reconcile_completion_evidence_v3',{p_project_key:project,p_limit:100});o.completion_evidence={data:completion.data,error:completion.error?.message||null};
 const legacyEvidence=await sb.rpc('contentflow_evidence_first_reconcile',{p_project_key:project,p_limit:80});o.evidence_first={data:legacyEvidence.data,error:legacyEvidence.error?.message||null};
 const evidence=await sb.rpc('contentflow_precycle_evidence_reconcile',{p_project_key:project});o.evidence_precycle={data:evidence.data,error:evidence.error?.message||null};
 const norm=await sb.rpc('contentflow_normalize_dispatchability',{p_project_key:project});o.normalize={data:norm.data,error:norm.error?.message||null};
 const dr=await sb.rpc('contentflow_dependency_release_reconcile',{p_project_key:project});o.dependency_release={data:dr.data,error:dr.error?.message||null};
 const reasons=await sb.rpc('contentflow_blocked_reason_reconcile',{p_project_key:project});o.blocked_reasons={data:reasons.data,error:reasons.error?.message||null};
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 o.recovery_pre=await callInternal(url,service,'contentflow-throughput-recovery',9000,{project_key:project});
 const pre=await sb.rpc('contentflow_master_reconcile',{p_project_key:project});o.pre_reconcile={data:pre.data,error:pre.error?.message||null};
 let runCore=true;
 if(project==='contentflow'){
   const signals=await collectAdmissionSignals(sb);const admission=evaluateAutonomyAdmission(signals);o.admission={...admission,telemetry_errors:signals.telemetryErrors};
   if(admission.admitted){o.planner=await callInternal(url,service,'contentflow-capacity-planner',5000)}else{o.planner={skipped:true,reason:'autonomy_admission_denied'};o.core={skipped:true,reason:'recovery_budget_aware_support_only',blockers:admission.blockers};runCore=false}
 }
 if(runCore){const c=await sb.rpc('contentflow_director_core_cycle_auto',{p_project_key:project});o.core={data:c.data,error:c.error?.message||null};}
 o.adaptive_dispatch=await callInternal(url,service,'contentflow-adaptive-dispatcher',7000,{project_key:project});
 const completion2=await sb.rpc('contentflow_reconcile_completion_evidence_v3',{p_project_key:project,p_limit:100});o.post_completion_evidence={data:completion2.data,error:completion2.error?.message||null};
 const waits2=await sb.rpc('contentflow_reconcile_durable_waits_v1',{p_project_key:project});o.post_durable_waits={data:waits2.data,error:waits2.error?.message||null};
 const legacyEvidencePost=await sb.rpc('contentflow_evidence_first_reconcile',{p_project_key:project,p_limit:80});o.evidence_first_post={data:legacyEvidencePost.data,error:legacyEvidencePost.error?.message||null};
 const post=await sb.rpc('contentflow_master_reconcile',{p_project_key:project});o.post_reconcile={data:post.data,error:post.error?.message||null};
 o.recovery_post=await callInternal(url,service,'contentflow-throughput-recovery',9000,{project_key:project});
 await sb.rpc('contentflow_state_invariant_reconcile',{p_project_key:project});
 const [{data:llm},{data:tool},{count:active},{data:lastCycle}]=await Promise.all([sb.rpc('contentflow_dispatchable_count',{p_project_key:project}),sb.rpc('contentflow_executable_tool_pending_count',{p_project_key:project}),sb.from('contentflow_builder_runs').select('id',{count:'exact',head:true}).eq('project_key',project).in('status',['claimed','running']),sb.from('director_cycle_runs').select('id,dispatched,status').eq('project_key',project).order('id',{ascending:false}).limit(1)]);o.health={llm_dispatchable:Number(llm||0),tool_executable:Number(tool||0),active_runs:Number(active||0),last_cycle:lastCycle?.[0]||null};return o
 }finally{try{await sb.rpc('contentflow_control_lease_release_v1',{p_project_key:project,p_holder_token:holder})}catch{}}}

Deno.serve(async(req)=>{const H={'content-type':'application/json','cache-control':'no-store'};if(!['GET','POST'].includes(req.method))return new Response('{}',{status:405,headers:H});const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return new Response(JSON.stringify({ok:false,error:'runtime_config_missing'}),{status:500,headers:H});const sb=createClient(url,service,{auth:{persistSession:false}});try{const now=new Date().toISOString();const {data:rows,error:e}=await sb.from('contentflow_build_backlog').select('project_key').in('status',['ready','planned','running','verification_required','blocked','deferred']);if(e)throw e;const projects=[...new Set((rows||[]).map((x:any)=>String(x.project_key||'')).filter(Boolean))];const results:any[]=[];for(const project of projects)results.push(await runProject(sb,url,service,project));const totalTool=results.reduce((a:number,x:any)=>a+Number(x?.health?.tool_executable||0),0);const evidenceWorkers=Math.min(2,Math.ceil(totalTool/4));if(evidenceWorkers>0)EdgeRuntime.waitUntil(Promise.all(Array.from({length:evidenceWorkers},()=>callInternal(url,service,'contentflow-evidence-tool-runner',120000))));const {count:reviews}=await sb.from('contentflow_review_work_queue').select('builder_run_id',{count:'exact',head:true}).eq('state','pending').lte('available_at',now);const since=new Date(Date.now()-30*60_000).toISOString();const {data:qa}=await sb.from('contentflow_nexo_request_metrics').select('model,success,semantic_success').eq('lane','qa').gte('created_at',since);let nreq=0,sem=0;const byModel:any={};for(const x of qa||[]){const m=String(x.model||'unknown');if(!byModel[m])byModel[m]={n:0,sem:0};byModel[m].n++;nreq++;if(x.semantic_success){byModel[m].sem++;sem++;}}let bestRate=0;for(const m of Object.keys(byModel))bestRate=Math.max(bestRate,byModel[m].sem/Math.max(1,byModel[m].n));const degraded=nreq>=20&&(sem/Math.max(1,nreq)<0.20||bestRate<0.20);const reviewCap=degraded?1:3;const n=Math.min(reviewCap,Number(reviews||0));if(degraded&&Number(reviews||0)>0){for(const p of projects){try{await sb.rpc('contentflow_learn_qa_health_degradation',{p_project_key:p,p_task_key:'review_queue',p_evidence:`qa_semantic_rate=${sem/Math.max(1,nreq)} best_rate=${bestRate} pending=${reviews}`})}catch{}}}if(n)EdgeRuntime.waitUntil(Promise.all(Array.from({length:n},()=>callInternal(url,service,'contentflow-rara',120000))));return new Response(JSON.stringify({ok:true,architecture:CONTROL_PLANE_ARCH,projects_discovered:projects,project_results:results,evidence_workers_scheduled:evidenceWorkers,review_workers_scheduled:n,qa_backpressure:{degraded,review_cap:reviewCap,total:nreq,semantic_ok:sem,best_rate:bestRate,by_model:byModel}}),{headers:H});}catch(err){return new Response(JSON.stringify({ok:false,architecture:CONTROL_PLANE_ARCH,error:String(err)}),{status:500,headers:H})}});
