--
-- PostgreSQL database dump
--

\restrict q7FtU1pVuPtmnKxn155YmHeAOxlZvB6dvI8kEXr10FasvpLhHOCtDoGE2tSzknC

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11 (Ubuntu 17.11-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: contentflow_capacity_phases; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contentflow_capacity_phases (phase, global_max, production_max, qa_max, recruitment_max, fallback_max, created_at) VALUES (1, 10, 6, 2, 1, 1, '2026-08-16 14:21:41.309687+00');
INSERT INTO public.contentflow_capacity_phases (phase, global_max, production_max, qa_max, recruitment_max, fallback_max, created_at) VALUES (2, 20, 10, 4, 4, 2, '2026-08-16 14:21:41.309687+00');
INSERT INTO public.contentflow_capacity_phases (phase, global_max, production_max, qa_max, recruitment_max, fallback_max, created_at) VALUES (3, 30, 15, 6, 6, 3, '2026-08-16 14:21:41.309687+00');


--
-- Data for Name: contentflow_capacity_state; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contentflow_capacity_state (id, active_phase, auto_scale, phase_started_at, min_phase_minutes, updated_at) VALUES (1, 2, false, '2026-08-16 23:45:00.223963+00', 360, '2026-08-17 01:55:27.543168+00');


--
-- Data for Name: contentflow_lane_models; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contentflow_lane_models (lane, primary_model, role, enabled, updated_at) VALUES ('production', 'Qwen/Qwen3-Max', 'Nexo recommended production reference', true, '2026-08-16 14:21:53.892523+00');
INSERT INTO public.contentflow_lane_models (lane, primary_model, role, enabled, updated_at) VALUES ('recruitment', 'MiniMax-M3', 'Nexo recommended recruitment', true, '2026-08-16 14:21:53.892523+00');
INSERT INTO public.contentflow_lane_models (lane, primary_model, role, enabled, updated_at) VALUES ('qa', 'Qwen/Qwen3-Max', 'QA/Judge primary promoted by health-based failover; Qwen3-30B quarantined after 0 recent semantic successes', true, '2026-08-23 13:09:49.560388+00');
INSERT INTO public.contentflow_lane_models (lane, primary_model, role, enabled, updated_at) VALUES ('fallback', 'Qwen/Qwen3-Max', 'Nexo recommended fallback/overflow', true, '2026-08-27 01:28:34.256223+00');


--
-- Data for Name: contentflow_retry_policies; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('capacity', true, 8, 30, 2.0, 300, 0.20, true, 'Transient Nexo lane saturation; back off rather than consume another immediate slot.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('judge', true, 5, 20, 2.0, 120, 0.15, false, 'Judge unavailable/unparseable; preserve builder work and retry review path.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('provider', true, 4, 30, 2.0, 180, 0.20, true, 'Transient provider failure; rotate model on retry.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('timeout', true, 4, 45, 2.0, 300, 0.20, true, 'Network/runtime timeout; bounded exponential backoff.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('state_recovery', true, 3, 15, 2.0, 60, 0.10, true, 'Recovered lease/orphan/stale state; short cool-down before a fresh claim.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('unknown', false, 0, 0, 1.0, 0, 0, false, 'Unknown failures are held for diagnosis instead of blind retry.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('quality_review', false, 0, 0, 1.0, 0, 0.10, false, 'Requires diagnosis/repair or strategy change before another execution.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('quality_gate', false, 0, 0, 1.0, 0, 0.10, false, 'Quality/cost gate is not a transient infrastructure failure.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('acceptance_evidence', false, 0, 0, 1.0, 0, 0.10, false, 'Acceptance/runtime-evidence failure requires repair, not blind retry.', '2026-08-16 20:00:10.241162+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('artifact_truncation', true, 3, 15, 2.0, 90, 0.10, true, 'Truncated model output is retryable with bounded backoff and model rotation; do not open a permanent unknown-error circuit.', '2026-08-26 22:52:28.520161+00');
INSERT INTO public.contentflow_retry_policies (error_class, retryable, max_attempts, initial_backoff_seconds, backoff_coefficient, max_backoff_seconds, jitter_ratio, switch_model_on_retry, notes, updated_at) VALUES ('artifact_defect', true, 3, 15, 2, 90, 0.15, true, NULL, '2026-08-27 03:03:50.508675+00');


--
-- Data for Name: director_canary_policy; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.director_canary_policy (id, project_key, bootstrap_parallelism, stable_parallelism, required_clean_cycles, max_recent_failure_rate, enabled, updated_at) VALUES (1, 'contentflow', 2, 4, 5, 0.25, true, '2026-08-22 21:20:20.021074+00');


--
-- Data for Name: director_control_policy; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.director_control_policy (project_key, enabled, desired_running, min_ready_buffer, no_progress_minutes, max_open_incidents, max_needs_help, max_state_mismatches, max_repeat_failures_24h, updated_at) VALUES ('contentflow', true, 4, 2, 15, 25, 0, 0, 3, '2026-08-22 21:20:20.021074+00');


--
-- Data for Name: director_operating_rules; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (13, 'worker_metrics_single_source_of_truth', 'Worker queue counters must be derived from contentflow_builder_runs: total_assignments = count(all runs), total_completions = count(status=completed), total_failures = count(status=failed). Never increment these counters independently from multiple event paths. Before ranking or assignment, enforce total_completions + total_failures <= total_assignments; if violated, rebuild counters from builder_runs and log a correction event.', 100, true, '2026-08-15 02:52:43.353273+00', '2026-08-15 02:52:43.353273+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (14, 'production_history_over_single_benchmark', 'Model selection must prioritize real contentflow_builder_runs outcomes by compatible task_type over one-shot benchmark scores. A benchmark with fewer than 5 comparable runs is exploratory evidence only and cannot outrank a model with sufficient productive history. Rank using recent compatible success rate, quality, latency and cost; apply circuit breaker after repeated task/model failures. Do not globally ban an approved worker solely for poor performance on an incompatible task type.', 100, true, '2026-08-15 02:53:03.730247+00', '2026-08-15 02:53:03.730247+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (2, 'completion_backlog_decomposition', 'For every non-completed ContentFlow task, Director must analyze latest Quality Gate failure, decompose missing work into minimal non-duplicative executable subtasks with explicit dependencies, assign each subtask to a compatible approved worker, and only retry the parent after all repair subtasks are completed. Keep all approved workers either RUNNING or READY with assigned productive work. Recompute this completion plan every cycle until base backlog reaches 100%.', 100, true, '2026-08-14 15:10:38.543948+00', '2026-08-14 15:10:38.543948+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (1, 'fresh10_pass_immediate_productive_assignment', 'Every Fresh-10 PASS >=85 is a persistent worker. Continuous chain rule: READY worker -> assign real compatible task -> RUNNING -> on finish automatically return to READY queue -> immediately receive next compatible task, repeating until project backlog is complete. Minimum operational concurrency is 8 whenever at least 8 approved workers and executable tasks exist; use all approved workers up to a safe dynamic ceiling, never treat 8 as a maximum. Every newly approved unique worker must be inserted or reactivated in director_worker_queue automatically. Recruitment must exclude already-approved workers, previously evaluated exact models, and same-family aliases/variants unless explicitly requested for a controlled comparison. Never create fake or duplicate work. Circuit-break the same failing task/model route after 3 failures and rotate the task to another compatible approved worker while keeping the failed worker eligible for other compatible work.', 100, true, '2026-08-14 14:47:08.836218+00', '2026-08-14 15:45:28.86101+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (3, 'preflight_verified_schema', 'Before any retry, verify referenced schema/components against live Supabase or dependency evidence. Never propagate invented artifacts.', 100, true, '2026-08-14 16:02:06.610145+00', '2026-08-14 16:02:06.610145+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (4, 'two_fail_strategy_change', 'After two materially identical failures, stop retrying the same strategy; update root-cause memory and change repair method before another attempt.', 100, true, '2026-08-14 16:02:06.610145+00', '2026-08-14 16:02:06.610145+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (5, 'concurrency_db_invariant', 'Every task reservation path must have an atomic claim plus a database-level invariant preventing duplicate active ownership.', 100, true, '2026-08-14 16:02:06.610145+00', '2026-08-14 16:02:06.610145+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (6, 'review_gate_fail_closed', 'Code completion/deploy must fail closed unless an independent review is recorded as approved at the database boundary.', 100, true, '2026-08-14 16:02:06.610145+00', '2026-08-14 16:02:06.610145+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (7, 'dependency_evidence_in_prompt', 'Worker prompts must include acceptance criteria and verified dependency evidence, not description alone.', 100, true, '2026-08-14 16:02:06.610145+00', '2026-08-14 16:02:06.610145+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (8, 'help_dependency_state_autosync', 'When a backlog task reaches completed, resolve any open HELP alert for that task. When all dependencies of a blocked parent are completed, automatically move the parent to READY and dispatch it without waiting for user intervention.', 100, true, '2026-08-14 17:59:58.522553+00', '2026-08-14 17:59:58.522553+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (9, 'continuous_completion_planning', 'Director planning is independent from worker availability: continuously analyze all non-completed ContentFlow work, blocked NO-GO/NEEDS_EVIDENCE and dependencies; pre-create the real non-duplicate completion backlog before workers become READY. Assignment is a separate step: whenever any approved worker becomes READY, immediately assign the highest-priority compatible prepared task. Never wait for READY capacity to decide what work is required to reach 100% completion.', 100, true, '2026-08-14 18:39:35.779307+00', '2026-08-14 18:39:35.779307+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (10, 'external_evidence_no_llm_retry', 'Tasks requiring external runtime/browser/deployment evidence must never be requeued to an LLM solely to fill worker capacity. Before emitting HELP for missing browser capability, first discover installed automation capabilities, attempt real execution, try an available equivalent runner, and distinguish deployment protection from runtime egress blocking or missing browser binaries. Record verified evidence attempts in director_external_evidence; only PASS evidence may unlock the dependent parent. BLOCKED evidence creates/updates one HELP alert and remains out of the LLM dispatcher.', 100, true, '2026-08-15 01:58:11.915977+00', '2026-08-15 01:58:49.808091+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (11, 'no_recursive_gap_descendants', 'Gap planner may decompose only root non-completed tasks. Never create gap_gap_* or deeper descendants. If a first-order gap cannot be resolved, rotate strategy/model or escalate the root task; do not recursively create another gap layer. Deferred invalid_recursive_gap records are non-executable and must never be dispatched.', 100, true, '2026-08-15 02:43:47.871391+00', '2026-08-15 02:43:47.871391+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (12, 'external_evidence_only_completion_mode', 'When all remaining non-completed root work is blocked solely on verified external evidence, enter EXTERNAL_EVIDENCE_ONLY mode: keep approved workers READY without manufacturing tasks; prohibit LLM retries and recursive gaps; maintain exactly one actionable HELP alert per external evidence blocker; retry only when a genuinely new capability/source becomes available. Exit this mode immediately when evidence passes, then unblock and dispatch dependent parents automatically.', 100, true, '2026-08-15 02:47:01.474327+00', '2026-08-15 02:47:01.474327+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (15, 'rara_escalation_policy', 'When the Director cannot repair a failure with known memory or the same failure persists, open a RARA incident automatically. RARA must verify evidence independently, diagnose root cause, execute only allowlisted reversible low-risk repairs automatically, validate the repair, write memory, and return control. Medium/high-risk destructive, credential, security-weakening, or data-loss actions require HELP/human approval.', 95, true, '2026-08-16 00:30:44.265869+00', '2026-08-16 00:30:44.265869+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (16, 'rara_always_available', 'RARA is always available to the Director. Each autonomous cycle must detect repair incidents and invoke RARA when an incident is open. RARA owns the incident until RESOLVED or justified HELP.', 99, true, '2026-08-16 00:31:46.30591+00', '2026-08-16 00:31:46.30591+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (17, 'hybrid_control_boundary', 'Use LLM reasoning only for semantic decisions such as decomposition, diagnosis, ranking context and repair proposals. State transitions, budgets, permissions, concurrency, dependency resolution, retries, rollback, acceptance gates and evidence verification must be deterministic and fail closed.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (18, 'event_ledger_checkpoint_recovery', 'Every meaningful task lifecycle transition must emit a correlated durable event with project_key, task_key, run/assignment identity, actor/model, outcome and timestamps. Recovery must resume from the last verified state and must not repeat already committed successful work.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (19, 'evidence_first_completion', 'No task may reach completed solely from a worker or judge assertion. Every acceptance criterion must map to reproducible artifact, test, runtime evidence, verified dependency evidence, or an explicitly allowed non-runtime proof. Missing required evidence means blocked/NEEDS_EVIDENCE, never PASS.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (20, 'end_to_end_traceability', 'Every productive run must be reconstructable end-to-end: task -> plan/dependencies -> assignment -> worker -> reviewer/judge -> tool/runtime calls -> quality -> cost -> evidence -> outcome -> recovery/error fingerprint. Uncorrelated runs are operational defects.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (21, 'guardrails_each_boundary', 'Apply independent guardrails at input, tool/action, output/review and deployment/completion boundaries. Security, secrets, destructive actions, schema assumptions and external side effects must fail closed when evidence or authorization is insufficient.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (22, 'github_source_of_truth_ci_gate', 'GitHub is the canonical source of truth for versioned ContentFlow code and reproducible configuration. Production-impacting code changes must flow through version control and CI evidence before deployment/acceptance when the relevant component is under GitHub management. Secrets must never be committed.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (23, 'master_director_project_adapter', 'New architecture work must preserve separation between the reusable Director core and project-specific adapters. Project-specific tools, policies, budgets, acceptance criteria, schemas and worker requirements belong in adapters/configuration rather than hard-coded Director logic.', 95, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (24, 'autonomy_measured_not_declared', 'Autonomy is accepted only from measured KPIs: worker utilization when eligible backlog exists, effective completion, autonomous recovery, recurrence by error fingerprint, evidence coverage, cost per accepted task and lead time. Claims of autonomy without measured evidence are invalid.', 100, true, '2026-08-16 01:31:30.723289+00', '2026-08-16 01:31:30.723289+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (25, 'nexorouter_lane_capacity_management', 'Use four NexoRouter lanes: production, qa, recruitment, fallback. Start phase 1 at 10 real concurrent API requests split 6/2/1/1. Respect lane/global semaphores, retry-after, bounded retries/backoff, 60s standard and up to 180s reasoning timeouts. Recruitment never steals production capacity; fallback is reserve. Record RPM/TPM, concurrency, latency avg/P95/max, 429/upstream, retry-after, timeouts, cost, token distributions and accepted-task rate by lane. Scale only from measured evidence.', 100, true, '2026-08-16 14:21:41.309687+00', '2026-08-16 14:21:41.309687+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (26, 'respect_retry_after', 'When NexoRouter returns retry-after, set task next_eligible_at accordingly, release capacity immediately, do not busy-wait or retry in a tight loop, and let another eligible task use the lane.', 100, true, '2026-08-16 14:23:18.974601+00', '2026-08-16 14:23:18.974601+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (27, 'evidence_producer_verifier_separation_v2', 'Evidence-producing work must execute on evidence_producer. tool_executor is reserved for deterministic verification/execution. Never gate a producer on evidence that only that producer can create. Human escalation is allowed only for explicit human/external approval or a genuinely unavailable prerequisite after bounded reconciliation.', 100, true, '2026-08-23 11:55:30.076292+00', '2026-08-23 11:55:30.076292+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (28, 'atomic_builder_claim_contract_v2', 'Every automatic transition to running on llm_artifact or evidence_producer must atomically create a claimed builder_run before dispatch. The global two-worker cap applies across both lanes. director-core assignments are autonomous and must be telemetered as assignment_mode=auto.', 100, true, '2026-08-23 11:56:24.234589+00', '2026-08-23 11:56:24.234589+00');
INSERT INTO public.director_operating_rules (id, rule_key, rule_text, target_pct, active, created_at, updated_at) VALUES (29, 'media_runtime_requires_real_executor_v1', 'Any task whose acceptance requires MP4, screen/media capture, rendered avatar/lipsync, final voice, GPU execution, subtitles synchronized to rendered media, keyframes from a rendered master, or runtime SHA-256 must not complete on llm_artifact. Split CPU/preproduction reasoning from runtime media execution. Runtime media must use tool_executor with a deterministic execution recipe or remain explicitly blocked on a real external executor. Never retry missing media capability through an LLM and never mark media DONE from prose.', 100, true, '2026-09-03 00:07:15.49401+00', '2026-09-03 00:07:15.49401+00');


--
-- Data for Name: director_repair_recipes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (2, '2026-08-16 14:14:29.277186+00', '2026-08-16 14:14:29.277186+00', 'contentflow', 'known_pgnet_queue_restart', 'pgnet_stuck', 'pg_net', 'pgnet_stuck:', 'restart_pg_net', '{}', 'low', 0.85, 0.95, 1, 0, 2, 'pgnet_queue_recovered', true, 'Known safe recovery: restart pg_net only when queue is non-empty/stuck.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (3, '2026-08-16 14:14:29.277186+00', '2026-08-16 14:14:29.277186+00', 'contentflow', 'known_review_gate_timeout', 'review_gate_stalled', 'review_gate', 'review_gate_stalled:', 'review_gate_reconcile', '{}', 'low', 0.85, 0.95, 1, 0, 2, 'review_gate_reconciled', true, 'Known safe recovery: reject stale unverified review and requeue with factual feedback.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (4, '2026-08-16 14:14:29.277186+00', '2026-08-16 14:14:29.277186+00', 'contentflow', 'known_runtime_state_mismatch', 'worker_backlog_state_mismatch', 'runtime_state', 'worker_backlog_state_mismatch:', 'runtime_state_reconcile', '{}', 'low', 0.85, 0.95, 1, 0, 2, 'state_reconciled', true, 'Known safe recovery: reconcile backlog/run/worker truth.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (5, '2026-08-16 14:14:29.277186+00', '2026-08-16 15:34:48.239135+00', 'contentflow', 'known_builder_timeout_requeue', 'builder_timeout', 'builder', 'builder_timeout:', 'requeue_failed_task', '{}', 'low', 0.85, 0.91, 2, 0, 2, 'task_requeued', false, 'Transport timeout is safe to retry when no active run exists; bounded by incident attempts.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (6, '2026-08-16 16:05:30.179424+00', '2026-08-16 19:36:42.232169+00', 'contentflow', 'learned_builder_failed_requeue_failed_task', 'builder_failed', 'builder', 'builder_failed:', 'requeue_failed_task', '{}', 'low', 0.8, 0.74, 26, 1, 2, 'Upon retry, the revised submission must demonstrate that guardrail decisions trigger structured evidence recording (e.g., via PlatformStore.record_evidence) that is externally observable and correlated to builder_run_id 1794.', true, 'Learned by RARA from resolved incident 32');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (16245, '2026-08-25 23:36:02.529185+00', '2026-08-28 11:58:20.157809+00', 'agent-academy-platform-v1', 'learned:fcc988eb8d23bec2fc20c4862c3f3295', 'progress_stall', 'director_control', 'progress_stall', 'progress_stall_reconcile', '{}', 'low', 0.80, 0.99, 733, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (7, '2026-08-17 01:52:00.907469+00', '2026-08-17 01:55:02.288783+00', 'contentflow', 'progress_stall_reconcile_v1', 'progress_stall', 'director_control', 'progress_stall', 'progress_stall_reconcile', '{}', 'low', 0.70, 0.60, 0, 3, 3, 'dispatchable_or_running_restored', false, 'Reconcile stale retry circuits and dependency anomalies; never remove real external dependencies.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (1, '2026-08-16 14:14:29.277186+00', '2026-08-24 20:12:15.830609+00', 'contentflow', 'known_stale_dispatch_collect', 'stale_dispatch', 'dispatcher', 'stale_dispatch:', 'collect_dispatches', '{}', 'low', 0.80, 0.99, 84, 0, 2, 'dispatch_not_pending', true, 'Known safe recovery: collect completed pg_net responses.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (596, '2026-08-24 20:18:49.803975+00', '2026-08-24 20:18:49.803975+00', 'avatar-platform-v1', 'transport_stale_dispatch_v1', 'stale_dispatch', 'dispatcher', 'stale_dispatch:', 'transport_recover', '{}', 'low', 0.60, 0.92, 0, 0, 5, 'dispatch_terminal_or_run_terminal', true, 'Deterministic response collection and fenced recovery for genuinely expired transport; never kills an activity before its activity deadline.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (10, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:a331e9706e967f48f7017e9f1d42d6d3', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_input_boundary_unverified_assumptions', 'requeue_failed_task', '{}', 'low', 0.80, 0.80000000000000000000, 3, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (11, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:19d7509cb1738cbc864dd86a39d188af', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_input_boundary_required_fields', 'requeue_failed_task', '{}', 'low', 0.80, 0.80000000000000000000, 3, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (12, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:1ba8649db5ae3a0c6f7c0fe8125488ce', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_input_boundary_secrets_pii_scan', 'requeue_failed_task', '{}', 'low', 0.80, 0.80000000000000000000, 3, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (13, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:18deda9ea6bb272ee53316fbe9f76d20', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_output_review_boundary_claim_verifiability_check', 'requeue_failed_task', '{}', 'low', 0.80, 0.83333333333333333333, 4, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (8, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:54547d42c7aa3acabd30314f27af6b09', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_tool_action_boundary', 'requeue_failed_task', '{}', 'low', 0.80, 0.83333333333333333333, 4, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');
INSERT INTO public.director_repair_recipes (id, created_at, updated_at, project_key, recipe_key, error_class, component, fingerprint_prefix, action_type, action_payload, risk_level, min_confidence, confidence, successes, failures, max_consecutive_failures, validation_type, enabled, notes) VALUES (9, '2026-08-19 18:37:46.619668+00', '2026-08-28 11:57:50.00906+00', 'contentflow', 'learned:b023f5899f025948cb07a7bb45a03718', 'builder_failed', 'builder', 'builder_failed:arch_guardrail_output_review_boundary_needs_evidence_classification', 'requeue_failed_task', '{}', 'low', 0.80, 0.83333333333333333333, 4, 0, 2, 'learned_incident_recurrence', true, 'Auto-promoted only after >=3 verified successful corrections and zero recorded correction failures.');


--
-- Data for Name: director_workflow_versions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.director_workflow_versions (version, project_key, status, architecture, created_at, activated_at, retired_at) VALUES ('director-core-v2', 'contentflow', 'active', '{"pattern": "serialized_durable_state_machine", "sources": ["Temporal", "LangGraph", "Microsoft Agent Framework", "OpenAI Agents SDK", "AutoGen lessons"], "principles": ["single_control_authority", "durable_checkpoints", "explicit_handoffs", "idempotent_transitions", "support_failure_boundaries", "canary_before_scale", "traceability"]}', '2026-08-16 19:49:14.153972+00', '2026-08-16 19:49:14.153972+00', NULL);


--
-- Name: director_operating_rules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.director_operating_rules_id_seq', 29, true);


--
-- Name: director_repair_recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.director_repair_recipes_id_seq', 36843, true);


--
-- PostgreSQL database dump complete
--

\unrestrict q7FtU1pVuPtmnKxn155YmHeAOxlZvB6dvI8kEXr10FasvpLhHOCtDoGE2tSzknC

