import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import path from 'node:path';
import os from 'node:os';
import { buildAvatarProjectState } from './avatar-project-state.mjs';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.JARVIS_PORT||4317), HOST=process.env.JARVIS_HOST||'127.0.0.1';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-sol';
const SUPABASE_URL=(process.env.SUPABASE_URL||'https://koqpyfvnprmirqviafzq.supabase.co').replace(/\/$/,'');
const SUPABASE_PUBLISHABLE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_KTxRW4wca-AcvP2tDve6Lw_PDI7WG_8';
const BUILD='2026-09-02-avatar-live-reconciler-v5.4';
const stateDir=path.join(os.homedir(),'.jarvis'), deviceTokenFile=path.join(stateDir,'director-device-token'), contextFile=path.join(stateDir,'active-context.json');
const PROJECTS={
 contentflow:{key:'contentflow',name:'Director / ContentFlow',aliases:['director','contentflow','orquestador']},
 avatar:{key:'avatar-platform-v1',name:'Responsable de Avatar',aliases:['avatar','proyecto avatar']},
 academy:{key:'agent-academy-platform-v1',name:'Responsable de Cygnus Academy / Skool',aliases:['academia','academy','skool','cygnus','cygnus academy']}
};
let runtimeOpenAIKey=process.env.OPENAI_API_KEY||'', directorDeviceToken=process.env.JARVIS_DIRECTOR_DEVICE_TOKEN||'', active={mode:'jarvis',project:'contentflow'};
try{if(!directorDeviceToken)directorDeviceToken=(await readFile(deviceTokenFile,'utf8')).trim()}catch{}
try{active={...active,...JSON.parse(await readFile(contextFile,'utf8'))}}catch{}
async function persistActive(){try{await mkdir(stateDir,{recursive:true});await writeFile(contextFile,JSON.stringify(active),'utf8')}catch{}}
function j(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body))}
async function readJson(req){let data='';for await(const chunk of req){data+=chunk;if(data.length>1_000_000)throw new Error('payload_too_large')}return data?JSON.parse(data):{}}
function errMsg(body,status){const c=body?.error?.message??body?.error_description??body?.message??body?.error??body?.raw;if(typeof c==='string'&&c.trim())return c.trim();try{if(c!=null)return JSON.stringify(c)}catch{}return `http_${status}`}
async function fetchJson(url,options={}){const r=await fetch(url,options),t=await r.text();let b;try{b=t?JSON.parse(t):{}}catch{b={raw:t}}if(!r.ok){const e=new Error(errMsg(b,r.status));e.status=r.status;e.apiBody=b;throw e}return b}
function wantsWeb(t=''){return /\b(web|internet|busca|buscar|noticias|actual|actualidad|hoy|ahora|precio|clima|mercado|últim[oa]s?|reciente)\b/i.test(t)}
async function openaiChat(messages,{context='',web=false}={}){if(!runtimeOpenAIKey)throw new Error('OPENAI_API_KEY_missing');const transcript=messages.map(m=>`${m.role==='assistant'?'Asistente':'Usuario'}: ${String(m.content||'')}`).join('\n');const payload={model:OPENAI_MODEL,store:false,instructions:`Eres Sol dentro de Jarvis Desktop. Habla en español, breve y operativo. Conversar no equivale a ejecutar. Nunca conviertas una pregunta, saludo, reporte o comentario en una acción. No inventes estados ni acciones. ${context} Responde únicamente al último mensaje del usuario.`,input:transcript};if(web)payload.tools=[{type:'web_search'}];const b=await fetchJson('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${runtimeOpenAIKey}`,'content-type':'application/json'},body:JSON.stringify(payload)});return b.output_text||b.output?.flatMap(o=>o.content||[]).map(c=>c.text).filter(Boolean).join('\n')||''}
function pinfo(id=active.project){return PROJECTS[id]||PROJECTS.contentflow}
function activeView(){const p=pinfo(active.project);return {...active,projectKey:p.key,projectName:p.name}}
async function bridge(action,extra={}){if(!directorDeviceToken)throw new Error('DIRECTOR_pairing_required');return fetchJson(`${SUPABASE_URL}/functions/v1/jarvis-director-bridge`,{method:'POST',headers:{authorization:`Bearer ${directorDeviceToken}`,apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({action,project_key:pinfo().key,...extra})})}
async function pairDirector(code){const r=await fetchJson(`${SUPABASE_URL}/functions/v1/jarvis-director-bridge`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'content-type':'application/json'},body:JSON.stringify({action:'pair',pairing_code:String(code||'').trim()})});directorDeviceToken=String(r.device_token||'');if(!directorDeviceToken)throw new Error('device_token_missing');await mkdir(stateDir,{recursive:true});await writeFile(deviceTokenFile,directorDeviceToken,{encoding:'utf8',mode:0o600});return{ok:true}}
function clean(t=''){return String(t).trim().replace(/^jarvis\s*[,;:]?\s*/i,'').trim()}
function detectProject(t=''){const c=clean(t).toLowerCase();for(const[id,p]of Object.entries(PROJECTS))if(p.aliases.some(a=>c.includes(a)))return id;return null}
function swSol(c){return /\b(hablar|habla|comun[ií]came|p[aá]same|conecta|con[eé]ctame|quiero hablar|vuelve|volver|regresa)\b.*\b(sol|chatgpt|contigo)\b|\b(sol|chatgpt)\b.*\b(hablar|conecta|con[eé]ctame|comun[ií]came|vuelve|volver|regresa)\b/i.test(c)}
function swJarvis(c){return /\b(vuelve|volver|regresa|regresar|p[aá]same|cambia|cambiar|hablar|conecta|con[eé]ctame)\b.*\bjarvis\b|\bjarvis\b.*\b(vuelve|volver|regresa|hablar|conecta|con[eé]ctame)\b/i.test(c)}
function swProject(c,p){return Boolean(p)&&/\b(hablar|habla|comun[ií]came|p[aá]same|conecta|con[eé]ctame|entra|abre|cambia|ve a|vamos a|selecciona|vuelve|volver|regresa)\b/i.test(c)}
function explicit(c){return /\b(ejecuta|ejecutar|corre|correr|inicia|iniciar|arranca|arrancar|lanza|lanzar|dispara|disparar)\b.*\b(ciclo|run)\b|\b(ciclo|run)\b.*\b(ejecuta|ejecutar|corre|correr|inicia|iniciar|arranca|arrancar|lanza|lanzar|dispara|disparar)\b/i.test(c)}
function informational(c){return /\?|\b(qu[eé]|cu[aá]l|cu[aá]nt|c[oó]mo|d[oó]nde|cu[aá]ndo|por qu[eé]|estado|status|reporte|reporta|tareas|avance|problemas|bloqueos|haciendo|trabajando|terminad|pendiente|necesita|pas[oó])\b/i.test(c)}
function classify(text=''){const c=clean(text),p=detectProject(c);if(swJarvis(c))return{type:'switch_jarvis',project:null,execute:false};if(swSol(c))return{type:'switch_sol',project:null,execute:false};if(swProject(c,p))return{type:'switch_project',project:p,execute:false};if(explicit(c))return{type:'project_cycle',project:p||active.project,execute:true};if((p||(active.mode==='project'?active.project:null))&&informational(c))return{type:'project_information',project:p||(active.mode==='project'?active.project:null),execute:false};return{type:'chat',project:null,execute:false}}
function selftest(){const cases=[['¿Qué está haciendo el Director?','project_information',false],['revisa el estado del Director','project_information',false],['reporte del Director','project_information',false],['¿cómo va Avatar?','project_information',false],['qué tareas tiene Skool','project_information',false],['ejecuta un ciclo del Director','project_cycle',true],['corre el run de Avatar','project_cycle',true],['lanza un ciclo de Skool','project_cycle',true],['quiero hablar con Sol','switch_sol',false],['comunícame con ChatGPT','switch_sol',false],['pásame con el Director','switch_project',false],['quiero hablar con Avatar','switch_project',false],['regresa con el Director','switch_project',false],['hablar con Skool','switch_project',false],['vuelve a Jarvis','switch_jarvis',false],['regresa a Jarvis','switch_jarvis',false],['hola','chat',false],['cuéntame una historia','chat',false],['revisa el Director','chat',false],['trabaja con Director','chat',false]];const prev={...active};active={mode:'jarvis',project:'contentflow'};const results=cases.map(([text,type,execute])=>{const got=classify(text);return{text,expected:type,got:got.type,executeExpected:execute,executeGot:Boolean(got.execute),pass:got.type===type&&Boolean(got.execute)===execute}});active=prev;return{ok:results.every(r=>r.pass),passed:results.filter(r=>r.pass).length,total:results.length,results}}
async function projectAnswer(text,messages,project){const p=pinfo(project),status=await bridge('project_status',{project_key:p.key}),safe=Array.isArray(messages)&&messages.length?messages:[{role:'user',content:text}];let operationalState=null;if(project==='avatar')operationalState=await buildAvatarProjectState({hubState:status});const backendState=project==='avatar'?{hub_internal:status,operational_global:operationalState}:status;const avatarRules=project==='avatar'?' Para Avatar, separa ESTADO HUB INTERNO de ESTADO OPERATIVO GLOBAL. Nunca llames canónico al estado si operational_global.canonical no es true; si hay conflicto o una fuente falta, dilo explícitamente.':'';const reply=await openaiChat(safe,{context:`Estás conversando como ${p.name}. Usa solo este estado real del backend para responder datos operativos: ${JSON.stringify(backendState)}. Si el estado no contiene el dato pedido, dilo claramente. No ejecutes nada.${avatarRules}`});return{type:'project_conversation',reply,project:status,operationalState,active:activeView()}}
async function route(text,messages=[]){const c=clean(text),p=detectProject(c);if(swJarvis(c)){active={mode:'jarvis',project:active.project};await persistActive();return{type:'switch',reply:'Volviste a Jarvis. Soy el centro de acceso a Sol y a los proyectos.',active:activeView()}}if(swSol(c)){active={mode:'sol',project:active.project};await persistActive();return{type:'switch',reply:'Conectado con Sol. Puedes hablar conmigo normalmente.',active:activeView()}}if(swProject(c,p)){active={mode:'project',project:p};await bridge('project_select',{project_key:pinfo(p).key});await persistActive();return{type:'switch',reply:`Conectado con ${pinfo(p).name}. Puedes conversar o pedir un reporte.`,active:activeView()}}const target=p||(active.mode==='project'?active.project:null);if(explicit(c)){const id=target||active.project,pi=pinfo(id),r=await bridge('project_cycle',{project_key:pi.key});return{type:'project_cycle',reply:r?.ok?`Ciclo de ${pi.name} solicitado correctamente.`:`${pi.name} reportó un problema al solicitar el ciclo.`,project:r,active:activeView()}}if(target&&(informational(c)||active.mode==='project'))return projectAnswer(text,messages,target);const safe=Array.isArray(messages)&&messages.length?messages:[{role:'user',content:text}];return{type:active.mode==='sol'?'sol':'chat',reply:await openaiChat(safe,{context:active.mode==='sol'?'El usuario decidió hablar directamente con Sol.':'Actúas como Jarvis, central de acceso a Sol y a los responsables de proyectos.',web:wantsWeb(c)}),model:OPENAI_MODEL,webEnabled:wantsWeb(c),active:activeView()}}
function health(){return{ok:true,service:'jarvis-desktop',build:BUILD,openaiConfigured:Boolean(runtimeOpenAIKey),webSearchEnabled:true,directorConfigured:Boolean(directorDeviceToken),directorMode:directorDeviceToken?'paired-device':'pairing-required',active:activeView(),availableProjects:Object.entries(PROJECTS).map(([id,v])=>({id,key:v.key,name:v.name})),openaiModel:OPENAI_MODEL}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/health')return j(res,200,health());if(req.method==='GET'&&url.pathname==='/api/selftest')return j(res,200,selftest());if(req.method==='POST'&&url.pathname==='/api/setup/openai'){const b=await readJson(req);if(!String(b.openaiApiKey||'').trim())return j(res,400,{error:'openai_key_required'});runtimeOpenAIKey=String(b.openaiApiKey).trim();return j(res,200,{ok:true,health:health()})}if(req.method==='POST'&&url.pathname==='/api/setup/pair'){const b=await readJson(req);await pairDirector(b.pairingCode);return j(res,200,{ok:true,health:health()})}if(req.method==='POST'&&url.pathname==='/api/classify'){const b=await readJson(req);return j(res,200,classify(String(b.text||'')))}if(req.method==='POST'&&url.pathname==='/api/jarvis'){const b=await readJson(req),text=String(b.text||'').trim(),messages=Array.isArray(b.messages)?b.messages.slice(-24):[];if(!text)return j(res,400,{error:'text_required'});return j(res,200,await route(text,messages))}if(req.method==='POST'&&url.pathname==='/api/chat'){const b=await readJson(req),messages=Array.isArray(b.messages)?b.messages.slice(-24):[];if(!messages.length)return j(res,400,{error:'messages_required'});return j(res,200,{reply:await openaiChat(messages,{web:wantsWeb(messages.at(-1)?.content||'')}),model:OPENAI_MODEL})}if(req.method==='GET'&&url.pathname==='/api/projects')return j(res,200,await bridge('projects'));if(req.method==='GET'&&url.pathname==='/api/director/status')return j(res,200,await bridge('project_status',{project_key:'contentflow'}));if(req.method==='POST'&&url.pathname==='/api/director/command'){const b=await readJson(req),command=String(b.command||'').trim();if(!explicit(clean(command)))return j(res,400,{error:'explicit_cycle_command_required'});return j(res,200,await bridge('project_cycle',{project_key:'contentflow'}))}if(req.method==='GET'&&(url.pathname==='/'||url.pathname==='/index.html')){const html=await readFile(path.join(__dirname,'ui.html'),'utf8');res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});return res.end(html)}return j(res,404,{error:'not_found'})}catch(error){const status=error?.message==='payload_too_large'?413:(Number.isInteger(error?.status)?error.status:500);return j(res,status,{error:String(error?.message||error),status,details:error?.apiBody||undefined})}});
server.on('error',e=>{if(e?.code==='EADDRINUSE'){console.error(`Jarvis no pudo iniciar: puerto ${PORT} ocupado.`);process.exitCode=3;return}console.error('Jarvis server error:',e)});
server.listen(PORT,HOST,()=>{const url=`http://${HOST}:${PORT}/`,t=selftest();console.log(`Jarvis Desktop: ${url} · ${BUILD} · router self-test ${t.passed}/${t.total}`);if(process.platform==='win32'){try{spawn('cmd.exe',['/c','start','',url],{detached:true,stdio:'ignore',windowsHide:true}).unref()}catch{}}});
