create table if not exists public.director_context_facts (
  id bigint generated by default as identity primary key,
  project_key text not null,
  fact_key text not null,
  version bigint not null,
  status text not null default 'active' check (status in ('active','superseded','retracted')),
  payload jsonb not null default '{}'::jsonb,
  source text not null,
  source_ref text,
  observed_at timestamptz not null default now(),
  expires_at timestamptz,
  verified boolean not null default false,
  supersedes_id bigint references public.director_context_facts(id),
  created_at timestamptz not null default now()
);

create unique index if not exists director_context_facts_one_active
  on public.director_context_facts(project_key,fact_key)
  where status='active';

create index if not exists director_context_facts_project_observed_idx
  on public.director_context_facts(project_key,observed_at desc);

alter table public.director_context_facts enable row level security;

create or replace function public.director_publish_context_fact(
  p_project_key text,
  p_fact_key text,
  p_payload jsonb,
  p_source text,
  p_source_ref text default null,
  p_observed_at timestamptz default now(),
  p_expires_at timestamptz default null,
  p_verified boolean default false
) returns public.director_context_facts
language plpgsql
security definer
set search_path=public
as $$
declare
  v_prev public.director_context_facts;
  v_next public.director_context_facts;
  v_version bigint;
begin
  if coalesce(btrim(p_project_key),'')='' or coalesce(btrim(p_fact_key),'')='' or coalesce(btrim(p_source),'')='' then
    raise exception 'project_key, fact_key and source are required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_project_key || ':' || p_fact_key,0));

  select * into v_prev
  from public.director_context_facts
  where project_key=p_project_key and fact_key=p_fact_key and status='active'
  order by version desc
  limit 1
  for update;

  select coalesce(max(version),0)+1 into v_version
  from public.director_context_facts
  where project_key=p_project_key and fact_key=p_fact_key;

  if v_prev.id is not null then
    update public.director_context_facts
      set status='superseded'
      where id=v_prev.id;
  end if;

  insert into public.director_context_facts(
    project_key,fact_key,version,status,payload,source,source_ref,
    observed_at,expires_at,verified,supersedes_id
  ) values (
    p_project_key,p_fact_key,v_version,'active',coalesce(p_payload,'{}'::jsonb),p_source,p_source_ref,
    coalesce(p_observed_at,now()),p_expires_at,coalesce(p_verified,false),v_prev.id
  )
  returning * into v_next;

  return v_next;
end;
$$;

revoke all on function public.director_publish_context_fact(text,text,jsonb,text,text,timestamptz,timestamptz,boolean) from public, anon, authenticated;
grant execute on function public.director_publish_context_fact(text,text,jsonb,text,text,timestamptz,timestamptz,boolean) to service_role;

create table if not exists public.director_browser_action_audit (
  id uuid primary key default gen_random_uuid(),
  project_key text not null,
  actor text not null,
  domain text not null,
  action text not null,
  risk_class text not null check (risk_class in ('low','high')),
  destructive boolean not null default false,
  requires_human_approval boolean not null default false,
  approval_status text not null check (approval_status in ('approved','pending','blocked')),
  request_payload jsonb not null default '{}'::jsonb,
  decision_reason text,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);

create index if not exists director_browser_action_audit_project_idx
  on public.director_browser_action_audit(project_key,created_at desc);

alter table public.director_browser_action_audit enable row level security;

create or replace function public.director_browser_action_gate(
  p_project_key text,
  p_actor text,
  p_domain text,
  p_action text,
  p_request_payload jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_high boolean;
  v_id uuid;
  v_status text;
begin
  v_high :=
    lower(coalesce(p_action,'')) ~ '(publish|post|delete|remove|archive|credential|password|oauth|payment|purchase|legal|accept|submit|send|change.*username|change.*email)'
    or lower(coalesce(p_domain,'')) ~ '(bank|broker|payment)';

  v_status := case when v_high then 'pending' else 'approved' end;

  insert into public.director_browser_action_audit(
    project_key,actor,domain,action,risk_class,destructive,
    requires_human_approval,approval_status,request_payload,decision_reason,decided_at
  ) values (
    p_project_key,p_actor,p_domain,p_action,
    case when v_high then 'high' else 'low' end,
    v_high,v_high,v_status,coalesce(p_request_payload,'{}'::jsonb),
    case when v_high then 'human_approval_required' else 'non_destructive_allowlisted_action' end,
    case when v_high then null else now() end
  ) returning id into v_id;

  return jsonb_build_object(
    'audit_id',v_id,
    'allowed',not v_high,
    'requires_human_approval',v_high,
    'approval_status',v_status,
    'risk_class',case when v_high then 'high' else 'low' end
  );
end;
$$;

revoke all on function public.director_browser_action_gate(text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.director_browser_action_gate(text,text,text,text,jsonb) to service_role;

comment on table public.director_context_facts is 'Versioned fresh-context facts with explicit supersession/provenance for Director and Jarvis.';
comment on table public.director_browser_action_audit is 'Fail-closed audit and human-approval gate for browser automation actions.';
