create table if not exists public.contentflow_wait_registry (
  backlog_task_id bigint primary key references public.contentflow_build_backlog(id) on delete cascade,
  project_key text not null,
  task_key text not null,
  wait_kind text not null check (wait_kind in ('timer','retry','dependency','capability','review','external_signal','terminal','unclassified')),
  wait_key text,
  wake_at timestamptz,
  terminal_reason text,
  generation bigint not null default 1,
  state text not null default 'waiting' check (state in ('waiting','released','terminal','unclassified')),
  classified_at timestamptz not null default now(),
  released_at timestamptz,
  evidence jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(project_key,task_key)
);
create index if not exists idx_contentflow_wait_registry_project_state on public.contentflow_wait_registry(project_key,state,wait_kind,wake_at);
alter table public.contentflow_wait_registry enable row level security;
revoke all on table public.contentflow_wait_registry from anon,authenticated;
grant select,insert,update,delete on table public.contentflow_wait_registry to service_role;

create table if not exists public.contentflow_durable_signal_ledger (
  id bigint generated by default as identity primary key,
  project_key text not null,
  task_key text not null,
  signal_key text not null,
  signal_id text not null,
  payload jsonb not null default '{}'::jsonb,
  producer text not null default 'unknown',
  created_at timestamptz not null default now(),
  unique(project_key,task_key,signal_key,signal_id)
);
create index if not exists idx_contentflow_signal_lookup on public.contentflow_durable_signal_ledger(project_key,task_key,signal_key,created_at desc);
alter table public.contentflow_durable_signal_ledger enable row level security;
revoke all on table public.contentflow_durable_signal_ledger from anon,authenticated;
grant select,insert on table public.contentflow_durable_signal_ledger to service_role;

create or replace function public.contentflow_record_durable_signal_v1(
  p_project_key text,p_task_key text,p_signal_key text,p_signal_id text,p_payload jsonb default '{}'::jsonb,p_producer text default 'control_plane'
) returns jsonb
language plpgsql security definer set search_path='public' as $$
declare v_id bigint; v_inserted boolean:=false;
begin
  if coalesce(auth.role(),'')<>'service_role' and session_user<>'postgres' then raise exception 'service_role_required'; end if;
  insert into public.contentflow_durable_signal_ledger(project_key,task_key,signal_key,signal_id,payload,producer)
  values(p_project_key,p_task_key,p_signal_key,p_signal_id,coalesce(p_payload,'{}'::jsonb),coalesce(nullif(p_producer,''),'control_plane'))
  on conflict(project_key,task_key,signal_key,signal_id) do nothing returning id into v_id;
  v_inserted:=v_id is not null;
  if v_id is null then select id into v_id from public.contentflow_durable_signal_ledger where project_key=p_project_key and task_key=p_task_key and signal_key=p_signal_key and signal_id=p_signal_id; end if;
  return jsonb_build_object('ok',true,'signal_id',v_id,'inserted',v_inserted,'deduplicated',not v_inserted);
end $$;
revoke all on function public.contentflow_record_durable_signal_v1(text,text,text,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.contentflow_record_durable_signal_v1(text,text,text,text,jsonb,text) to service_role;

create or replace function public.contentflow_reconcile_durable_waits_v1(p_project_key text default 'contentflow')
returns jsonb language plpgsql security definer set search_path='public' as $$
declare x record; v_kind text; v_key text; v_wake timestamptz; v_terminal text; v_state text; v_classified int:=0; v_released int:=0; v_unclassified int:=0; v_incidents int:=0;
begin
  if coalesce(auth.role(),'')<>'service_role' and session_user<>'postgres' then raise exception 'service_role_required'; end if;
  for x in
    select b.*,
      (select min(rs.next_retry_at) from public.contentflow_retry_state rs where rs.backlog_task_id=b.id and rs.next_retry_at is not null) retry_at,
      (select min(rs.circuit_open_until) from public.contentflow_retry_state rs where rs.backlog_task_id=b.id and rs.circuit_state='open' and rs.circuit_open_until is not null) circuit_until
    from public.contentflow_build_backlog b where b.project_key=p_project_key and b.status='deferred'
  loop
    v_kind:=null; v_key:=null; v_wake:=null; v_terminal:=null; v_state:='waiting';
    if coalesce(x.blocked_reason,'') like 'OBSOLETE%' then
      v_kind:='terminal'; v_terminal:=x.blocked_reason; v_state:='terminal';
    elsif x.next_eligible_at is not null then
      v_kind:=case when x.retry_at is not null or x.circuit_until is not null then 'retry' else 'timer' end;
      v_wake:=greatest(x.next_eligible_at,coalesce(x.retry_at,x.next_eligible_at),coalesce(x.circuit_until,x.next_eligible_at));
      v_key:=coalesce(x.blocked_reason,'scheduled_wakeup');
    elsif exists(select 1 from jsonb_array_elements_text(coalesce(x.depends_on,'[]'::jsonb)) d(dep) where not exists(select 1 from public.contentflow_build_backlog z where z.project_key=x.project_key and z.task_key=d.dep and z.status='completed')) then
      v_kind:='dependency';
      select d.dep into v_key from jsonb_array_elements_text(coalesce(x.depends_on,'[]'::jsonb)) d(dep) where not exists(select 1 from public.contentflow_build_backlog z where z.project_key=x.project_key and z.task_key=d.dep and z.status='completed') order by d.dep limit 1;
    elsif x.retry_at is not null or x.circuit_until is not null then
      v_kind:='retry'; v_wake:=greatest(coalesce(x.retry_at,'-infinity'::timestamptz),coalesce(x.circuit_until,'-infinity'::timestamptz)); v_key:='retry_policy';
    elsif coalesce(x.execution_lane,'llm_artifact') in ('tool_executor','evidence_producer') and not public.contentflow_tool_execution_capability_ready(x.project_key,x.task_key) then
      v_kind:='capability'; v_key:=coalesce(x.execution_lane,'evidence_producer');
    elsif exists(select 1 from public.contentflow_review_work_queue q join public.contentflow_builder_runs r on r.id=q.builder_run_id where r.backlog_task_id=x.id and q.state in ('pending','claimed')) then
      v_kind:='review'; v_key:='rara_review';
    else
      v_kind:='unclassified'; v_state:='unclassified'; v_key:='missing_causal_wakeup'; v_unclassified:=v_unclassified+1;
    end if;

    insert into public.contentflow_wait_registry(backlog_task_id,project_key,task_key,wait_kind,wait_key,wake_at,terminal_reason,state,evidence,updated_at)
    values(x.id,x.project_key,x.task_key,v_kind,v_key,v_wake,v_terminal,v_state,jsonb_build_object('status',x.status,'workflow_state',x.workflow_state,'blocked_reason',x.blocked_reason,'classified_from','durable_wait_signal_contract_v1'),now())
    on conflict(backlog_task_id) do update set
      wait_kind=excluded.wait_kind,wait_key=excluded.wait_key,wake_at=excluded.wake_at,terminal_reason=excluded.terminal_reason,
      generation=case when public.contentflow_wait_registry.wait_kind is distinct from excluded.wait_kind or public.contentflow_wait_registry.wait_key is distinct from excluded.wait_key or public.contentflow_wait_registry.wake_at is distinct from excluded.wake_at then public.contentflow_wait_registry.generation+1 else public.contentflow_wait_registry.generation end,
      state=excluded.state,classified_at=case when public.contentflow_wait_registry.wait_kind is distinct from excluded.wait_kind then now() else public.contentflow_wait_registry.classified_at end,
      released_at=null,evidence=public.contentflow_wait_registry.evidence||excluded.evidence,updated_at=now();
    v_classified:=v_classified+1;
  end loop;

  update public.contentflow_wait_registry w set state='released',released_at=now(),updated_at=now()
  where w.project_key=p_project_key and w.state='waiting' and exists(
    select 1 from public.contentflow_build_backlog b where b.id=w.backlog_task_id and b.status='deferred' and (
      (w.wait_kind in ('timer','retry') and w.wake_at is not null and w.wake_at<=now() and not exists(select 1 from public.contentflow_retry_state rs where rs.backlog_task_id=b.id and rs.circuit_state='open' and coalesce(rs.circuit_open_until,now()+interval '1 day')>now()))
      or (w.wait_kind='dependency' and not exists(select 1 from jsonb_array_elements_text(coalesce(b.depends_on,'[]'::jsonb)) d(dep) where not exists(select 1 from public.contentflow_build_backlog z where z.project_key=b.project_key and z.task_key=d.dep and z.status='completed')))
      or (w.wait_kind='capability' and public.contentflow_tool_execution_capability_ready(b.project_key,b.task_key))
      or (w.wait_kind='external_signal' and exists(select 1 from public.contentflow_durable_signal_ledger s where s.project_key=b.project_key and s.task_key=b.task_key and s.signal_key=w.wait_key))
    )
  );
  get diagnostics v_released=row_count;

  update public.contentflow_build_backlog b set status='ready',blocked_reason=null,next_eligible_at=now(),updated_at=now()
  where b.project_key=p_project_key and b.status='deferred' and exists(select 1 from public.contentflow_wait_registry w where w.backlog_task_id=b.id and w.state='released' and w.released_at>=now()-interval '1 minute');

  if v_unclassified>0 and not exists(select 1 from public.director_repair_incidents where project_key=p_project_key and error_fingerprint='durable_wait_unclassified:v1' and status in ('open','analyzing','repairing','validating','needs_help')) then
    insert into public.director_repair_incidents(project_key,component,error_class,error_fingerprint,symptom,evidence,risk_level,status,max_attempts,requires_human,root_cause,proposed_action)
    values(p_project_key,'director_control','durable_wait_unclassified','durable_wait_unclassified:v1','Deferred work exists without timer, dependency, retry, capability, review, signal, or terminal cause',jsonb_build_object('unclassified',v_unclassified),'medium','open',3,false,'Planner emitted a deferred state without a durable wake contract','Classify source generation and either register a durable cause or mark it terminal/obsolete');
    get diagnostics v_incidents=row_count;
  end if;

  update public.contentflow_wait_registry w set state='released',released_at=coalesce(released_at,now()),updated_at=now() where w.project_key=p_project_key and w.state in ('waiting','unclassified') and exists(select 1 from public.contentflow_build_backlog b where b.id=w.backlog_task_id and b.status<>'deferred');

  return jsonb_build_object('architecture','DURABLE_WAIT_SIGNAL_CONTRACT_V1','classified',v_classified,'released',v_released,'unclassified',v_unclassified,'incident_created',v_incidents,'waiting',(select count(*) from public.contentflow_wait_registry where project_key=p_project_key and state='waiting'),'terminal',(select count(*) from public.contentflow_wait_registry where project_key=p_project_key and state='terminal'));
end $$;
revoke all on function public.contentflow_reconcile_durable_waits_v1(text) from public,anon,authenticated;
grant execute on function public.contentflow_reconcile_durable_waits_v1(text) to service_role;
