-- Reconciled from supabase_migrations.schema_migrations by recovery automation.
-- Source: canonical production migration history; no credentials are emitted.

create extension if not exists pgcrypto;

create table if not exists public.trading_sqx_bridge_devices (
  id uuid primary key default gen_random_uuid(),
  device_name text not null,
  token_hash text not null unique,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','REVOKED','OFFLINE')),
  capabilities jsonb not null default '{}'::jsonb,
  last_health jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.trading_sqx_bridge_pairing_codes (
  code_hash text primary key,
  label text,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.trading_sqx_bridge_commands (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.trading_sqx_bridge_devices(id) on delete cascade,
  command_type text not null check (command_type in ('list_projects','list_strategies','list_databanks','get_strategy_stats','run_project','stop_project')),
  payload jsonb not null default '{}'::jsonb,
  state text not null default 'QUEUED' check (state in ('QUEUED','CLAIMED','SUCCEEDED','FAILED','CANCELLED')),
  claim_nonce uuid,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  result jsonb,
  error text,
  updated_at timestamptz not null default now()
);

create index if not exists trading_sqx_bridge_commands_device_state_created_idx
  on public.trading_sqx_bridge_commands(device_id, state, created_at);

create table if not exists public.trading_sqx_bridge_events (
  id bigint generated by default as identity primary key,
  device_id uuid references public.trading_sqx_bridge_devices(id) on delete set null,
  command_id uuid references public.trading_sqx_bridge_commands(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.trading_sqx_bridge_devices enable row level security;
alter table public.trading_sqx_bridge_pairing_codes enable row level security;
alter table public.trading_sqx_bridge_commands enable row level security;
alter table public.trading_sqx_bridge_events enable row level security;

comment on table public.trading_sqx_bridge_devices is 'StrategyQuant local bridge devices; service-role/Edge Function access only.';
comment on table public.trading_sqx_bridge_commands is 'Allowlisted StrategyQuant MCP commands queued by Director and claimed by local bridge.';
comment on table public.trading_sqx_bridge_events is 'Audit trail for StrategyQuant bridge activity.';
